// Generated by emit_vectors_qualifier.py from the strict qualifier-rewrite transformer.
const std::string nativeSelect = "C0 03 0C 01 28 01 00 01 00 01 01 64 00 00 00 64 00 00 00 00";
const std::string transformedSelect = "C0 03 0C 01 17 02 01 01 01 64 00 00 00 64 00 00 00 00 C9 01 01 64 00 00 00 64 00 00 00 00";
const std::string transformedFrame = "05 64 24 C4 0A 00 01 00 CC 64 C0 C0 03 0C 01 17 02 01 01 01 64 00 00 00 64 00 9F 5B 00 00 00 C9 01 01 64 00 00 00 64 00 00 00 00 56 5C";
