#!/usr/bin/env python3
"""HISTORICAL (three-pipe layout, model only): places T in pipe 2, which cannot load on the two-pipe switch, and
T's ports (read/ports.p4) are now pipe-1 ports. The live composite is core/response_only/compose.py.

Compose T (read_queue_timing.p4) and the B' response path (protocol/case4_response_path.p4) into one
multi-pipe Tofino-1 program, per STEP3_DESIGN.md option C: T in pipe 2, the response path's egress in
pipe 0 (every front-panel port, including FORWARD 9 and RELAY 64, is in pipe 0).

  p0 = the response path's own pipeline: its 1-stage forwarding ingress (standing in for N, which is
       not part of this composition) and its padder + transport-mapper egress (the real role E).
  p1 = a drop-only placeholder (M's pipe; M is not part of this composition).
  p2 = T, unchanged.

T's released originals leave on ports 9 / 64 with bypass_egress = 0, so they cross into pipe 0's egress
and pass the response path's transform exactly once. T's holds (326, 327) and clones (324) are pipe-2
ports and run pipe 2's (empty) egress instead. Neither program bridges metadata ingress-to-egress: T
emits the original Ethernet frame with its own headers invalid, and the response path's egress parser
starts at Ethernet, so the cross-pipe interface needs no adaptation.

Every top-level name of each source is prefixed with its role (t_, r_), as core/ordinary/compose.py does;
nothing else is changed. Sources are read from the committed files.

  python3 compose_t_response.py <out.p4>
"""
import hashlib
import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
T_SRC = HERE / 'read_queue_timing.p4'
R_SRC = HERE.parent.parent / 'protocol' / 'case4_response_path.p4'


def inline(text, base):
    """Inline local "..." includes (role prefixing below must see their declarations)."""
    return re.sub(r'^#include "([^"]+)"\n', lambda m: (base / m[1]).read_text() + '\n', text, flags=re.M)


def strip_main(text):
    text = re.sub(r'^#include <[^>]+>\n', '', text, flags=re.M)
    text = re.sub(r'^Pipeline\(.*?\)\s*\w+\s*;\s*', '', text, flags=re.M | re.S)
    return re.sub(r'^Switch\(.*?\)\s*main\s*;\s*', '', text, flags=re.M)


def role(text, ns):
    names = set(re.findall(r'\b(?:header|struct|parser|control|typedef\s+[\w<>]+)\s+(\w+)', text))
    names.update(re.findall(r'\bconst\s+[\w<>]+\s+(\w+)\s*=', text))
    names -= {'apply'}
    pattern = r'\b(' + '|'.join(sorted(names, key=len, reverse=True)) + r')\b'
    return re.sub(pattern, lambda m: ns + '_' + m[0], text), sorted(names)


def generate():
    t_text = strip_main(inline(T_SRC.read_text(), HERE))
    r_text = strip_main(R_SRC.read_text())
    t_out, t_names = role(t_text, 't')
    r_out, r_names = role(r_text, 'r')
    stub = """
/* p1 placeholder (M's pipe is not part of this composition): drop everything. */
struct x_hdr_t { }
struct x_meta_t { }
parser x_IgParser(packet_in pkt, out x_hdr_t hdr, out x_meta_t m, out ingress_intrinsic_metadata_t ig) {
    state start { pkt.extract(ig); pkt.advance(PORT_METADATA_SIZE); transition accept; } }
control x_Ingress(inout x_hdr_t hdr, inout x_meta_t m, in ingress_intrinsic_metadata_t ig,
                  in ingress_intrinsic_metadata_from_parser_t p, inout ingress_intrinsic_metadata_for_deparser_t md,
                  inout ingress_intrinsic_metadata_for_tm_t tm) { apply { md.drop_ctl = 3w1; } }
control x_IgDeparser(packet_out pkt, inout x_hdr_t hdr, in x_meta_t m,
                     in ingress_intrinsic_metadata_for_deparser_t md) { apply { } }
parser x_EgParser(packet_in pkt, out x_hdr_t hdr, out x_meta_t m, out egress_intrinsic_metadata_t eg) {
    state start { pkt.extract(eg); transition accept; } }
control x_Egress(inout x_hdr_t hdr, inout x_meta_t m, in egress_intrinsic_metadata_t eg,
                 in egress_intrinsic_metadata_from_parser_t p, inout egress_intrinsic_metadata_for_deparser_t md,
                 inout egress_intrinsic_metadata_for_output_port_t port) { apply { } }
control x_EgDeparser(packet_out pkt, inout x_hdr_t hdr, in x_meta_t m,
                     in egress_intrinsic_metadata_for_deparser_t md) { apply { } }
"""
    source = ('/* GENERATED by read/compose_t_response.py -- do not edit. T (pipe 2) + B\' response path\n'
              '   (pipe 0 egress), STEP3_DESIGN.md option C. */\n#include <core.p4>\n#include <tna.p4>\n'
              + r_out + '\n' + t_out + '\n' + stub +
              '\nPipeline(r_IgParser(), r_Ingress(), r_IgDeparser(), r_EgParser(), r_Egress(), r_EgDeparser()) p0;\n'
              'Pipeline(x_IgParser(), x_Ingress(), x_IgDeparser(), x_EgParser(), x_Egress(), x_EgDeparser()) p1;\n'
              'Pipeline(t_IngressParser(), t_Ingress(), t_IngressDeparser(), t_EmptyEgressParser(), t_EmptyEgress(),'
              ' t_EmptyEgressDeparser()) p2;\n'
              'Switch(p0, p1, p2) main;\n')
    collisions = sorted(set(t_names) & set(r_names))
    meta = dict(inputs={str(p.relative_to(HERE.parent.parent.parent.parent.parent)): hashlib.sha256(p.read_bytes()).hexdigest()
                        for p in (T_SRC, HERE / 'ports.p4', HERE / 'probe_shell.p4', R_SRC)},
                source_sha256=hashlib.sha256(source.encode()).hexdigest(),
                renamed=dict(t=len(t_names), r=len(r_names)), name_collisions_before_prefixing=collisions)
    return source, meta


if __name__ == '__main__':
    out = Path(sys.argv[1])
    src, meta = generate()
    out.write_text(src)
    out.with_suffix('.inputs.json').write_text(json.dumps(meta, indent=2) + '\n')
    print('wrote', out, json.dumps(meta['renamed']), 'collisions before prefixing:', meta['name_collisions_before_prefixing'])
