"""Local Tofino-1 model run of operate_slice_capture.p4 (F1): the real OPERATE admission + mirror clone path.

Functional model execution only: not hardware, not timing. The mirror session is configured on the LOCAL model.
operate_slice_capture.p4 is generated by make_operate_slice.py --capture-hb: read_queue_timing.p4's parser,
deparser (with the F1 Mirror emit), hold_operate, admit_operate_held and the PKTGEN_RETURN / T_IN OPERATE
branches verbatim; only HB_RETURN is replaced by an export (OP blocker -> port 1, anything else -> port 2).

  integration/core/launch_model.sh -p integration/evidence/mirror_f1_01/compile_capture_local/out \
     -o integration/evidence/mirror_f1_01/model_NN -P "1 2 64 324 325 326" -d integration/read/model_drive_operate_clone.py
"""
import os
import struct
import sys
import time
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path[:0] = [str(HERE.parent / 'core')]
from model_driver import Model, Report, gc  # noqa: E402

T_IN, PKTGEN_RETURN, HB_RETURN, RELAY, BLK_OUT, HELD_OUT, SID = 325, 324, 326, 64, 1, 2, 7
ETH = bytes.fromhex('0a0000000002' '0a0000000001') + b'\x88\xb5'
PAYLOAD = bytes(range(200, 230))                                # OP_FRAME's payload in queue_sim.py
BUDGET = 240000                                                 # params default_action budget
EPOCH = 5


def operate(epoch=EPOCH):
    return struct.pack('!IIIBBH', epoch, 0x0000abcd, 0x01000000, 12, 0, 0) + ETH + PAYLOAD


def ladder(role, gen, budget):
    return struct.pack('!BBHI', role, 0, gen, budget)


def strip_pad(got, want):
    return got[:len(want)] == want and not any(got[len(want):])


m = Model(ports=[], enable=False)
rep = Report(os.environ['PROG'], operate=operate().hex())
m.enable_ports([BLK_OUT, HELD_OUT, RELAY])
time.sleep(2.0)
rep.add('ports_enabled', {}, m.port_errors, ok=not m.port_errors)
target = gc.Target(device_id=0, pipe_id=0xffff)
mc = m.table('$mirror.cfg', raw=True)
mc.entry_add(target, [mc.make_key([gc.KeyTuple('$sid', SID)])], [mc.make_data([
    gc.DataTuple('$direction', str_val='INGRESS'), gc.DataTuple('$ucast_egress_port', PKTGEN_RETURN),
    gc.DataTuple('$ucast_egress_port_valid', bool_val=True), gc.DataTuple('$session_enable', bool_val=True)], '$normal')])
WATCH = [BLK_OUT, HELD_OUT, RELAY]


def reg(name):
    r = m.register_read('Ingress.' + name, 0)
    return [v for k, v in r.items() if k.endswith('.f1')][0][2]   # pipe 2 = T's pipe


def one_operate(label, gen):
    out = m.exchange(T_IN, operate(), WATCH, timeout=3.0, quiet=1.0)
    time.sleep(1.0)                                              # a late duplicate would land here
    late = m.capture(WATCH, timeout=1.0, quiet=0.5)
    blk = out[BLK_OUT] + late[BLK_OUT]
    held = out[HELD_OUT] + late[HELD_OUT]
    relay = out[RELAY] + late[RELAY]
    rep.add(label + '_op_gen_allocated', gen, reg('op_gen_alloc_reg'))
    rep.add(label + '_admitting_pass_is_one_blocker', 1, len(blk), frames=[x.hex() for x in blk])
    rep.add(label + '_blocker_bytes', True, bool(blk) and strip_pad(blk[0], ladder(13, gen, BUDGET) + PAYLOAD))
    rep.add(label + '_clone_admitted_exactly_once_as_held', 1, len(held), frames=[x.hex() for x in held])
    rep.add(label + '_held_is_role16_gen_plus_pristine_original', True,
            bool(held) and strip_pad(held[0], ladder(16, gen, 0) + ETH + PAYLOAD))
    rep.add(label + '_nothing_released_to_relay', 0, len(relay))
    rep.add(label + '_op_t0_armed', True, reg('op_t0_reg') & 1 == 1, op_t0=reg('op_t0_reg'))


one_operate('first', 1)
one_operate('second', 2)

# policy off: the verbatim T_IN arm passes the OPERATE straight to the relay and requests NO clone
m.set_default('Ingress.params', 'Ingress.set_params',
              dict(da=2000000, readiness=12000000, cap=16000000, gap=800000, op_j=2400000, budget=BUDGET, enabled=0))
out = m.exchange(T_IN, operate(), WATCH, timeout=3.0, quiet=1.0)
rep.add('off_passthrough_once_to_relay', 1, len(out[RELAY]), frames=[x.hex() for x in out[RELAY]])
rep.add('off_relay_bytes_are_original', True, bool(out[RELAY]) and strip_pad(out[RELAY][0], ETH + PAYLOAD))
rep.add('off_no_clone_no_blocker', [0, 0], [len(out[BLK_OUT]), len(out[HELD_OUT])])
rep.add('off_op_gen_unchanged', 2, reg('op_gen_alloc_reg'))

# negative control: policy back on, mirror session removed -> the admitting blocker still appears, but no
# held original does, so the held frames above exist only because of the Mirror() clone.
m.set_default('Ingress.params', 'Ingress.set_params',
              dict(da=2000000, readiness=12000000, cap=16000000, gap=800000, op_j=2400000, budget=BUDGET, enabled=1))
mc.entry_del(target, [mc.make_key([gc.KeyTuple('$sid', SID)])])
out = m.exchange(T_IN, operate(), WATCH, timeout=3.0, quiet=1.0)
late = m.capture(WATCH, timeout=1.0, quiet=0.5)
rep.add('nosession_blocker_still_once', 1, len(out[BLK_OUT] + late[BLK_OUT]))
rep.add('nosession_no_held_original', 0, len(out[HELD_OUT] + late[HELD_OUT]))
sys.exit(0 if rep.finish(os.path.join(os.environ['OUT'], 'cases.json')) else 1)
