// GENERATED by make_operate_slice.py from read_queue_timing.p4 -- do not edit. Test fixture for
// the local model: the OPERATE admission / mirror clone / release path, copied verbatim.
// T's READ timing role, queue-resident design (not the heartbeat/recirculation design in
// read_timing.p4). Real ACK/response/OPERATE originals stay resident in their hold queues
// (LADDER qid6/qid4, OP_LADDER qid2); only blocker tokens (qid7/qid5/qid3) repeat the timing
// circulation, matching defense4_rrc_bor_unified12.p4's qid7/6/5/4/3/2 ladder
// (integration/INTEGRATION_CONTRACT.md section 1; the heartbeat design is a correctness
// reference only, never the base). Invariants (a)-(g): see
// integration/read/tests/test_t_queue_invariants.py and
// DNP3_Timing_Size_Integration_Prompt.md section 4, Phase C. The whole file still does not compile
// (unresolved bf-p4c crash); what has been compiled and model-run is listed in
// read/TIMING_QUEUE_MIGRATION_STATUS.md.
#include <core.p4>
#include <tna.p4>
#include "ports.p4"
// New port, local to this file only (not added to ports.p4): where the mirror clone of a
// request admission recirculates (pipe 2 local 68; queue_sim.py PKTGEN_PORT = 324).
const PortId_t PKTGEN_RETURN = 9w324;
// The clone itself (F1): mirror_type 1 requests it; IngressDeparser emits it to the mirror session the
// control plane binds to PKTGEN_RETURN ($mirror.cfg). The session id travels in metadata because
// bf-p4c rejects a constant session selector (defense4_rrc_bor_unified12.p4, same pattern).
const bit<3> MIRROR_TYPE_CLONE = 1;
const MirrorId_t CLONE_SESSION_ID = 10w7;

// Ladder roles (queue_sim.py ROLE dict): 11 ACK blocker, 12 response blocker, 13 OPERATE
// blocker, 14 held ACK, 15 held response, 16 held OPERATE.
const bit<8> ROLE_ACK_BLK  = 11; const bit<8> ROLE_RESP_BLK = 12; const bit<8> ROLE_OP_BLK  = 13;
const bit<8> ROLE_ACK_HELD = 14; const bit<8> ROLE_RESP_HELD = 15; const bit<8> ROLE_OP_HELD = 16;

// tev.kind wire values, identical to read_timing.p4's own T_IN convention.
const bit<8> KIND_REQUEST = 9; const bit<8> KIND_ACK = 10; const bit<8> KIND_RESPONSE = 11;
const bit<8> KIND_OPERATE = 12; const bit<8> KIND_RESET = 4;

// Outcome counters (outcomes register index), named to match test_t_queue_invariants.py's
// out(sim, 'OUT_*') lookups via sim.consts().
const bit<32> OUT_UNMATCHED = 0; const bit<32> OUT_HELD_REWAIT = 1; const bit<32> OUT_ACK_COMMIT = 2;
const bit<32> OUT_RESP_RELEASE = 3; const bit<32> OUT_RESP_DUP_DROP = 4; const bit<32> OUT_OP_RELEASE = 5;
const bit<32> OUT_TOKEN_STALE = 6; const bit<32> OUT_HELD_STALE_FLUSH = 7; const bit<32> OUT_ACK_FALLBACK = 8;
const bit<32> OUT_RESP_FALLBACK = 9; const bit<32> OUT_TOKEN_TMO = 10; const bit<32> OUT_HELD_OFF_FLUSH = 11;
const bit<32> OUT_TOKEN_OFF = 12; const bit<32> OUT_REQ_BYPASS = 13;
// No outcome recorded on this pass (md.outcome_code's initial value; outcome_count has no entry for it).
const bit<8> OUT_NONE = 0xff;

header tev_t { bit<32> epoch; bit<32> wgen; bit<32> t0q; bit<8> kind; bit<8> stage; bit<16> reserved; }
header ladder_t { bit<8> role; bit<8> child; bit<16> generation; bit<32> budget; }
header clone_hdr_t { bit<32> tag; }
header ethernet_t { bit<48> dst; bit<48> src; bit<16> type; }
struct header_t { pktgen_timer_header_t timer; clone_hdr_t clone; tev_t tev; ladder_t ladder; ethernet_t eth; }
struct gen_mask_t { bit<32> gen; bit<32> mask; }

struct metadata_t {
    // da/readiness/gap/op_j are config action-data (set_params); cap is accepted (the test always
    // passes it) but not stored -- nothing in this design uses it as a deadline.
    bit<32> da; bit<32> readiness; bit<32> gap; bit<32> op_j; bit<32> budget_cap; bit<32> enabled;
    bit<32> now;
    bit<32> in_epoch; bit<32> cur_epoch; bit<32> quarantine;
    bit<8> q_reset;   // 1 on an enabled RESET pass: quarantine_access records hdr.tev.epoch
    bit<32> cur_gen; bit<32> new_gen; bit<32> t0_v;
    bit<32> ack_done_g; bit<32> resp_done_g;
    bit<32> ack_commit_at_v; bit<32> resp_deadline_v; bit<32> resp_target;
    // Narrow: these only ever hold a 3-bit child mask or a 0/1 flag -- bit<32> would occupy 4x the
    // PHV this design doesn't have to spare (see TIMING_QUEUE_MIGRATION_STATUS.md's PHV finding).
    bit<8> resp_seen_mask; bit<8> dup;
    // 1 when this held ACK / held response may commit on this pass; the input to ack_done_try /
    // resp_done_try, computed before the register so the register needs no later dependent write.
    bit<8> ack_go; bit<8> resp_go;
    // Tofino's conditional-execution gateway cannot evaluate a live comparison between two fully
    // dynamic values (bf-p4c: "condition too complex ... one operand must be constant"), so every
    // now-vs-deadline check here is precomputed as delta = now - deadline, then its sign bit is
    // matched by a one-entry ternary table into a 0/1 ready flag -- read_timing.p4's own
    // deadline_deltas/heartbeat_eligibility pattern (see the *_sign tables). The
    // deltas/deadlines need the full dynamic range; the *_ready outputs are 0/1 flags and are
    // narrowed accordingly.
    bit<32> deadline_da; bit<32> da_delta; bit<8> da_ready;
    bit<32> deadline_readiness; bit<32> readiness_delta; bit<8> readiness_ready;
    bit<32> gap_delta; bit<8> gap_ready;
    bit<32> op_t0_masked; bit<32> op_deadline; bit<32> op_delta; bit<8> op_ready;
    bit<32> op_gen; bit<32> op_done_g; bit<32> op_t0_v;
    bit<32> clone_tag; bit<32> token_gen; bit<32> token_domain;
    MirrorId_t clone_ses;
    // The one outcome this pass records; bumped by the single outcome_count table at the end of apply.
    bit<8> outcome_code;
}

parser IngressParser(packet_in pkt, out header_t hdr, out metadata_t md,
                     out ingress_intrinsic_metadata_t ig_intr_md) {
    state start {
        pkt.extract(ig_intr_md); pkt.advance(PORT_METADATA_SIZE);
        transition select(ig_intr_md.ingress_port) {
            T_IN : parse_tev;
            HELD_RETURN : parse_ladder;
            HB_RETURN : parse_ladder;
            PKTGEN_RETURN : parse_clone;
            default : parse_timer;
        }
    }
    state parse_tev {
        pkt.extract(hdr.tev);
        transition select(hdr.tev.kind, hdr.tev.reserved) {
            (9, 0) : opaque_ethernet;
            (10, 0) : opaque_ethernet;
            (11, 0) : opaque_ethernet;
            (12, 0) : opaque_ethernet;
            (4, 0) : opaque_ethernet;
            default : reject;
        }
    }
    state parse_ladder {
        pkt.extract(hdr.ladder);
        transition select(hdr.ladder.role) {
            11 : accept;
            12 : accept;
            13 : accept;
            14 : opaque_ethernet;
            15 : opaque_ethernet;
            16 : opaque_ethernet;
            default : reject;
        }
    }
    // The clone always carries this pass's pristine original bytes (tag + the T_IN wire format it
    // mirrored). Only an OPERATE-admission clone (tev.kind 12) is used for anything; a
    // request-admission clone (kind 9, READ's ACK/response blockers never need this) is parsed the
    // same way and then simply dropped in the apply block.
    state parse_clone {
        pkt.extract(hdr.clone); pkt.extract(hdr.tev);
        transition select(hdr.tev.kind, hdr.tev.reserved) {
            (9, 0) : opaque_ethernet;
            (12, 0) : opaque_ethernet;
            default : reject;
        }
    }
    state parse_timer { pkt.extract(hdr.timer); transition accept; }
    state opaque_ethernet { pkt.extract(hdr.eth); transition accept; }
}

control Ingress(inout header_t hdr, inout metadata_t md,
                in ingress_intrinsic_metadata_t ig_intr_md,
                in ingress_intrinsic_metadata_from_parser_t ig_prsr_md,
                inout ingress_intrinsic_metadata_for_deparser_t ig_dprsr_md,
                inout ingress_intrinsic_metadata_for_tm_t ig_tm_md) {
    action set_params(bit<32> da, bit<32> readiness, bit<32> cap, bit<32> gap, bit<32> op_j,
                      bit<32> budget, bit<32> enabled) {
        md.da = da; md.readiness = readiness; md.gap = gap; md.op_j = op_j;
        md.budget_cap = budget; md.enabled = enabled;
    }
    table params {
        actions = { set_params; }
        default_action = set_params(2000000, 12000000, 16000000, 800000, 2400000, 240000, 1); size = 1;
    }
    action clock_sample() { md.now = ((bit<32>)ig_prsr_md.global_tstamp) & 32w0xffffff00; }
    table clock { actions = { clock_sample; } default_action = clock_sample(); size = 1; }
    Register<bit<32>, bit<1>>(1, 0) op_gen_alloc_reg;
    RegisterAction<bit<32>, bit<1>, bit<32>>(op_gen_alloc_reg) op_gen_peek = {
        void apply(inout bit<32> value, out bit<32> out_value) { out_value = value; }
    };
    RegisterAction<bit<32>, bit<1>, bit<32>>(op_gen_alloc_reg) op_gen_bump = {
        void apply(inout bit<32> value, out bit<32> out_value) { value = value + 1; out_value = value; }
    };
    Register<bit<32>, bit<1>>(1, 0) op_done_reg;
    RegisterAction<bit<32>, bit<1>, bit<32>>(op_done_reg) op_done_read = {
        void apply(inout bit<32> value, out bit<32> out_value) { out_value = value; }
    };
    RegisterAction<bit<32>, bit<1>, bit<32>>(op_done_reg) op_done_try = {
        void apply(inout bit<32> value, out bit<32> out_value) {
            out_value = value;
            if (md.op_ready == 1) { value = md.op_gen; }
        }
    };
    Register<bit<32>, bit<1>>(1, 0) op_t0_reg;
    RegisterAction<bit<32>, bit<1>, bit<32>>(op_t0_reg) op_t0_read = {
        void apply(inout bit<32> value, out bit<32> out_value) { out_value = value; }
    };
    RegisterAction<bit<32>, bit<1>, bit<32>>(op_t0_reg) op_t0_arm = {
        void apply(inout bit<32> value, out bit<32> out_value) {
            value = md.now | 32w1;
            out_value = value;
        }
    };
    RegisterAction<bit<32>, bit<1>, bit<32>>(op_t0_reg) op_t0_clear = {
        void apply(inout bit<32> value, out bit<32> out_value) { value = 0; out_value = 0; }
    };
    Register<bit<32>, bit<4>>(16, 0) outcomes;
    RegisterAction<bit<32>, bit<4>, bit<32>>(outcomes) bump_outcome = {
        void apply(inout bit<32> value, out bit<32> out_value) { value = value + 1; out_value = value; }
    };
    action count(bit<32> code) { md.outcome_code = (bit<8>)code; }
    action bump(bit<4> idx) { bump_outcome.execute(idx); }
    table outcome_count {
        key = { md.outcome_code : exact; }
        actions = { bump; NoAction; }
        const entries = {
            0 : bump(0); 1 : bump(1); 2 : bump(2); 3 : bump(3); 4 : bump(4); 5 : bump(5); 6 : bump(6);
            7 : bump(7); 8 : bump(8); 9 : bump(9); 10 : bump(10); 11 : bump(11); 12 : bump(12); 13 : bump(13);
        }
        default_action = NoAction(); size = 16;
    }
    action passthrough_tev_relay() { hdr.tev.setInvalid(); ig_tm_md.ucast_egress_port = RELAY_PORT; }
    action hold_operate() {
        hdr.tev.setInvalid(); hdr.eth.setInvalid();
        hdr.ladder.setValid();
        hdr.ladder.role = ROLE_OP_BLK; hdr.ladder.child = 0;
        hdr.ladder.generation = (bit<16>)md.op_gen; hdr.ladder.budget = md.budget_cap;
        ig_tm_md.ucast_egress_port = HB_RETURN; ig_tm_md.qid = 3;
        // A single Tofino action stage supports one ALU op per field; a mask-then-OR is two, so
        // this relies on one plain OR instead (op_gen is expected well under 0x10000 in any one
        // generation-counter lifetime exercised here -- an actual wraparound-safe generation-tag
        // encoding is a follow-up, not needed for this evidence). Not an add: once the Mirror emit
        // made clone_tag live, bf-p4c split op_gen over two 16-bit containers and rejected the
        // carrying add (2 PHV sources + a constant); a bitwise OR splits per container.
        ig_dprsr_md.mirror_type = 1; md.clone_tag = md.op_gen | 32w0x10000;
        md.clone_ses = CLONE_SESSION_ID;
    }
    action admit_operate_held() {
        md.op_gen = op_gen_peek.execute(0);
        hdr.clone.setInvalid(); hdr.tev.setInvalid();
        hdr.ladder.setValid();
        hdr.ladder.role = ROLE_OP_HELD; hdr.ladder.child = 0;
        hdr.ladder.generation = (bit<16>)md.op_gen; hdr.ladder.budget = 0;
        ig_tm_md.ucast_egress_port = HB_RETURN; ig_tm_md.qid = 2;
    }
    action drop_clone() { ig_dprsr_md.drop_ctl = 1; }
    action keep_blocking(PortId_t port, bit<5> qid) {
        hdr.ladder.budget = hdr.ladder.budget - 1;
        ig_tm_md.ucast_egress_port = port; ig_tm_md.qid = qid;
    }
    action stop_blocking() { ig_dprsr_md.drop_ctl = 1; }
    action stop_blocking_stale() { ig_dprsr_md.drop_ctl = 1; count(OUT_TOKEN_STALE); }
    action stop_blocking_tmo() { ig_dprsr_md.drop_ctl = 1; count(OUT_TOKEN_TMO); }
    action stop_blocking_off() { ig_dprsr_md.drop_ctl = 1; count(OUT_TOKEN_OFF); }
    action compute_op_t0_masked() { md.op_t0_masked = md.op_t0_v & 32w0xfffffffe; }
    action compute_op_deadline() { md.op_deadline = md.op_t0_masked + md.op_j; }
    action compute_op_delta() { md.op_delta = md.now - md.op_deadline; }
    action set_op_ready(bit<8> v) { md.op_ready = v; }
    table op_sign {
        key = { md.op_delta : ternary; }
        actions = { set_op_ready; }
        const entries = { 32w0 &&& 32w0x80000000 : set_op_ready(1); }
        default_action = set_op_ready(0); size = 1;
    }
    action release_operate() {
        hdr.ladder.setInvalid();
        ig_tm_md.ucast_egress_port = RELAY_PORT;
    }
    action rewait_operate() {
        ig_tm_md.ucast_egress_port = HB_RETURN; ig_tm_md.qid = 2;
        count(OUT_HELD_REWAIT);
    }
    action flush_operate_stale() {
        hdr.ladder.setInvalid(); ig_tm_md.ucast_egress_port = RELAY_PORT;
        count(OUT_HELD_STALE_FLUSH);
    }
    action flush_operate_off() {
        hdr.ladder.setInvalid(); ig_tm_md.ucast_egress_port = RELAY_PORT;
        count(OUT_HELD_OFF_FLUSH);
    }
    action unmatched() { ig_dprsr_md.drop_ctl = 1; count(OUT_UNMATCHED); }
    apply {
        ig_tm_md.bypass_egress = 0;
        md.outcome_code = OUT_NONE;
        params.apply(); clock.apply();
        if (ig_intr_md.ingress_port == PKTGEN_RETURN) {
            if (hdr.tev.kind == KIND_OPERATE && md.enabled != 0) { admit_operate_held(); }
            else { drop_clone(); }
        }
        // GLUE: T_IN with only the policy-off OPERATE passthrough and the OPERATE admission arm.
        else if (ig_intr_md.ingress_port == T_IN) {
            if (md.enabled == 0) { passthrough_tev_relay(); }
            else if (hdr.tev.kind == KIND_OPERATE) {
                md.op_gen = op_gen_bump.execute(0);
                op_t0_arm.execute(0);
                hold_operate();
            }
            else { unmatched(); }
        }
        else if (ig_intr_md.ingress_port == HB_RETURN) {
            // GLUE (--capture-hb): export every HB_RETURN arrival, ladder intact, for counting.
            if (hdr.ladder.role == ROLE_OP_BLK) { ig_tm_md.ucast_egress_port = 9w1; }
            else { ig_tm_md.ucast_egress_port = 9w2; }
        }
        else { unmatched(); }
        outcome_count.apply();
    }
}

control IngressDeparser(packet_out pkt, inout header_t hdr, in metadata_t md,
                       in ingress_intrinsic_metadata_for_deparser_t ig_dprsr_md) {
    // No-arg Mirror(): the typed Mirror(mirror_type) constructor errors "Inconsistent mirror
    // selectors" on Tofino-1 (defense4_rrc_bor_unified12.p4, IgDeparser).
    Mirror() clone_mirror;
    apply {
        if (ig_dprsr_md.mirror_type == MIRROR_TYPE_CLONE) {
            clone_mirror.emit<clone_hdr_t>(md.clone_ses, { md.clone_tag });
        }
        pkt.emit(hdr);
    }
}
#include "probe_shell.p4"

Pipeline(IngressParser(), Ingress(), IngressDeparser(), EmptyEgressParser(),
         EmptyEgress(), EmptyEgressDeparser()) pipe;
Switch(pipe) main;
