#!/usr/bin/env python3
"""Generate paper/rewrite/FINAL_FIGURES.md from the figures themselves.

Reads each figure's provenance sidecar (written by defense4/timing/analysis/figstyle.py),
hashes the copies that actually sit in paper/rewrite/figures/timing/, and greps the LaTeX to
confirm each one is referenced. Regenerating beats hand-editing: the hashes cannot drift away
from the files after a figure is rebuilt.

Usage:  python3 pipeline/make_final_figures.py
"""
import hashlib
import json
import pathlib
import re
import subprocess
import sys

REWRITE = pathlib.Path(__file__).resolve().parent.parent
REPO = REWRITE.parent.parent
FIGDIR = REWRITE / "figures" / "timing"
SRCDIR = REPO / "defense4" / "timing" / "figures" / "source"
PUBDIR = REPO / "defense4" / "timing" / "figures" / "publication"
EVID = REPO / "defense4" / "timing" / "evidence" / "final_read_sbo"

# figure stem -> (number, manuscript section, LaTeX label, float type)
PLACEMENT = [
    ("fig01_clrt_read_select_before_after", 1, "Evaluation, RO1 (read timing)",
     "fig:clrt-dist", "figure* (double column, 7.16 in)"),
    ("fig02_clrt_ecdf_before_after", 2, "Evaluation, RO1 (read timing)",
     "fig:clrt-ecdf", "figure (single column, 3.5 in)"),
    ("fig03_timing_feature_overlap_before_after", 3, "Evaluation, RO1 (read timing)",
     "fig:overlap", "figure* (double column, 7.16 in)"),
    ("fig04_sbo_operate_timing_by_j", 4, "Evaluation, RO2 (control timing)",
     "fig:operate-j", "figure (single column, 3.5 in)"),
    ("fig05_timing_leakage_summary", 5, "Evaluation, RO1 (read timing)",
     "fig:leakage", "figure* (double column, 7.16 in)"),
]

TEX = sorted(REWRITE.glob("*.tex"))


def sha(p):
    return hashlib.sha256(pathlib.Path(p).read_bytes()).hexdigest()


def referenced(stem):
    hits = [t.name for t in TEX
            if re.search(r"includegraphics\{figures/timing/%s\}" % re.escape(stem),
                         t.read_text())]
    return hits


def rel(p):
    """Repository-relative path. Sidecar inputs are already relative; leave them alone."""
    p = str(p)
    if not p.startswith("/"):
        return p
    return str(pathlib.Path(p).resolve()).replace(str(REPO) + "/", "")


def main():
    out = []
    w = out.append
    w("# FINAL_FIGURES.md — the five figures of the timing paper")
    w("")
    w("Generated by `pipeline/make_final_figures.py`; do not hand-edit, regenerate it after")
    w("rebuilding a figure. All five live directly in `figures/timing/`: the vector PDF is the")
    w("manuscript source, the PNG a 600 dpi preview. Every one is produced only by")
    w("`defense4/timing/reproduce.sh` from the six raw captures, and no plotting script")
    w("contains a measured value as a literal (checked by `defense4/timing/tests/test_timing.py`).")
    w("")
    w("Figures follow the `ieee-paper-figures` conventions: rendered at final printed size and")
    w("included with `\\includegraphics{...}` at natural size (never rescaled, which would drop")
    w("the 9 pt type below the IEEE floor), 9 pt Times New Roman embedded, opaque white,")
    w("`alessandretti-nature` palette with line style and marker also distinguishing every")
    w("series so the figures read in greyscale. Each figure carries **only its legend and axis")
    w("labels**; everything explanatory is in the LaTeX caption.")
    w("")
    w("**The policy value is 4 ms, for both READ and SBO.** READ CLRT and SBO CLRT are both")
    w("normalized to 4.001 ms (Figures 1 and 2), and the master-visible SBO operation time")
    w("holds at 4.00 ms across every configured hold J (Figure 4). The 20 ms and 24 ms release")
    w("offsets are internal anchors, not the normalized quantity; they are not plotted.")
    w("")
    w("**The arms.** Every before/after figure compares *Timing OFF* with *Timing ON*. Both")
    w("ran the same unified switch binary with the size-shaping datapath active, so Timing OFF")
    w("is **not** an unmodified native SEL-751 baseline; the comparison isolates the")
    w("timing-mode change within one binary.")
    w("")
    w("In-manuscript figure numbers are assigned by LaTeX and currently follow the three")
    w("section diagrams, so file `fig01` prints as Fig. 4 and so on; the file numbers below are")
    w("the stable identifiers.")
    w("")
    w("---")
    for stem, num, section, label, float_kind in PLACEMENT:
        prov = json.loads((PUBDIR / ("%s.provenance.json" % stem)).read_text())
        cap = prov["caption_draft"]
        short = cap.split(". ")[0].rstrip(".") + "."
        pdf, png = FIGDIR / ("%s.pdf" % stem), FIGDIR / ("%s.png" % stem)
        refs = referenced(stem)
        w("")
        w("## Figure %d — %s" % (num, short.rstrip(".")))
        w("")
        w("| | |")
        w("|---|---|")
        w("| PDF | `%s` |" % rel(pdf))
        w("| PNG | `%s` |" % rel(png))
        w("| Manuscript section | %s, `\\label{%s}` |" % (section, label))
        w("| Float | %s |" % float_kind)
        w("| Referenced by LaTeX | **%s** |"
          % ("yes — %s" % ", ".join("`%s`" % r for r in refs) if refs else "NO"))
        w("| Source script | `%s` — `%s` |"
          % (rel(SRCDIR / ("%s.py" % stem)), sha(SRCDIR / ("%s.py" % stem))))
        for i in prov["inputs"]:
            w("| Input | `%s` — `%s` |" % (rel(i["path"]), i["sha256"]))
        w("| SHA-256 PDF | `%s` |" % sha(pdf))
        w("| SHA-256 PNG | `%s` |" % sha(png))
        w("| Figure data | `%s` |" % rel(PUBDIR / ("%s_data.csv" % stem)))
        w("")
        w("**Caption.** %s" % cap)
        w("")
        w("**Statistics.** %s" % prov["statistical_method"])
    w("")
    w("---")
    w("")
    w("## Raw captures behind every figure")
    w("")
    w("| capture | sha256 |")
    w("|---|---|")
    for line in sorted((EVID / "MANIFEST.sha256").read_text().splitlines()):
        if "raw_pcaps" in line:
            h, p = line.split()
            w("| `%s` | `%s` |" % (p.split("/")[-1], h))
    w("")
    (REWRITE / "FINAL_FIGURES.md").write_text("\n".join(out) + "\n")
    missing = [s for s, *_ in PLACEMENT if not referenced(s)]
    print("wrote FINAL_FIGURES.md for %d figures; unreferenced: %s"
          % (len(PLACEMENT), missing or "none"))
    return 1 if missing else 0


if __name__ == "__main__":
    sys.exit(main())
