#!/usr/bin/env python3.8
# =============================================================================
#  four_queue_dequeue_oracle_setup.py — control plane for the FOUR-QUEUE
#  on-chip TM dequeue-order oracle (p4/four_queue_dequeue_oracle.p4).
#
#  Runs ON THE SWITCH against the loaded program (bfruntime localhost:50052):
#
#    SDE=/home/decps/Downloads/bf-sde-9.13.2
#    SP=$SDE/install/lib/python3.8/site-packages
#    PYTHONPATH=$SP:$SP/tofino python3.8 four_queue_dequeue_oracle_setup.py --config
#
#  ---------------------------------------------------------------------------
#  THE MECHANISM, IN ONE PARAGRAPH
#
#  There is NO port-level scheduling enable on Tofino-1 (tf1.tm.port.sched_cfg
#  carries only max_rate_enable and scheduling_speed), so releasing N queues via
#  per-queue scheduling_enable is inescapably N separate writes — and draining
#  32 x 64-byte frames at 25G takes about 1.7 us, the SAME ORDER as the driver's
#  per-entry write latency. Enable ORDER could therefore decide drain order while
#  the experiment looked perfectly healthy. The fix is to leave every queue
#  scheduling-enabled and gate the PORT instead: a port-level max-rate shaper
#  sits ABOVE the queue scheduler, so ONE write holds all four queues and ONE
#  write makes them all servable at the same instant. The scheduler, not the
#  control plane's write order, then decides.
#
#  THE GATE MUST BE ON THE PORT THAT OWNS THE QUEUES (dp8). Gating any other
#  port would hold traffic the dp8 scheduler had ALREADY ordered, and would pass
#  meaninglessly. That is refused here, not warned about.
#
#  ---------------------------------------------------------------------------
#  WHY THE PACKETS COME FROM INSIDE THE CHIP
#
#  All traffic is generated by the Tofino packet generator on dp68 with a
#  one-shot TIMER trigger. No host is involved: dp11 is never configured, Hulk is
#  never contacted, no raw socket and no packet capture is required, and the
#  release-to-first-dequeue window is never gated by host scheduling. The 128
#  generated packets are byte-identical copies of ONE buffer template and differ
#  only in the hardware packet_id, so the ROLE assignment lives entirely in the
#  128-entry tbl_role map that this script rewrites, from a recorded seed, before
#  every trial. That is what makes the observed order provably not the emission
#  order: emission order is fixed by hardware at 0,1,2,...,127.
#
#  ---------------------------------------------------------------------------
#  SCOPE. This script configures and measures SCHEDULER PRIORITY only. It says
#  nothing about reservoir depth or about recirculation empty gaps; those remain
#  separate evidence. See reports/FOUR_QUEUE_DEQUEUE_ORACLE_REPORT.md.
#
#  Ports touched: dp8 (loopback, owns the queues) and dp68 (packet generator).
#  dp11 is NOT configured. Hulk is NOT contacted. sudo is NEVER invoked.
# =============================================================================
"""four_queue_dequeue_oracle_setup.py — control plane for the four-queue on-chip
dequeue-order oracle.

Modes (at least one required):
  --config          one-time: dp8 MAC-near loopback, per-queue shapers cleared,
                    packet generator port/buffer/app configured (app DISABLED).
  --verify-only     read everything back, print PASS/FAIL, write NOTHING.
  --priorities      write the four max_priority values for --priority-mode.
  --role-map        write the 128-entry packet_id -> role map for --seed.
  --gate-close      close the dp8 port gate (2 writes: shape, then arm).
  --gate-open       open it (ONE write).
  --gate-status     read both gate tables back.
  --occupancy       per-queue usage / watermark / drop counters.
  --reset-trace     zero the three accounting registers.
  --trace-dump      read the trace out and write it to --out as JSON.
  --trial           THE WHOLE TRIAL, in one process: ASSERT CLEAN, reset, map,
                    priorities, close gate, generate, preload gate check,
                    release, read trace, MANDATORY CLEANUP, write JSON. Doing it
                    in one process keeps the preload-check-to-release window
                    short and makes the release a single local gRPC write.
  --shaper-probe    screen ONE dp8 PORT-shaper setting (--gate-unit/--gate-rate/
                    --gate-burst) with EQUAL queue priorities. Characterization
                    only; run/run_four_queue_oracle.sh --shaper-sweep drives it.
  --assert-clean    read the five clean facts; exit non-zero if any is wrong.
  --cleanup         run the mandatory cleanup path on its own.
  --restore-dp8     put dp8's scheduling config back to its original state.
  --dry-run         no gRPC at all: print the plan and exit.

TRIAL ISOLATION. Every trial asserts a clean start (and REFUSES to run on a
dirty switch) and runs the cleanup in a `finally`, so a trial that ends INVALID
leaves the switch exactly as a trial that ends PASS does. The five clean facts
are: all four queue occupancies 0, total_dequeues 0, trace_entries_written 0,
trace_overflow 0, pktgen disabled.

Exit status is non-zero if any check FAILs. Prints a PASS/FAIL table and one
JSON line `FQDQ {...}`. Python 3.8; no numpy (not installed on the switch).
"""
import argparse
import json
import random
import sys
import time

# ---------------------------------------------------------------------------
# Constants. Every one mirrors p4/four_queue_dequeue_oracle.p4; the cited line
# is where it is defined there. PROVENANCE for the bfrt names is the SDE schema
# install/share/bf_rt_shared/bf_rt_{tm,pktgen}_tf1.json (9.13.1), and for the
# packet generator sequence pkgsrc/p4-examples/p4_16_programs/tna_pktgen/test.py.
# ---------------------------------------------------------------------------
PROG_DEFAULT = "four_queue_dequeue_oracle"

PORT_L = 8       # .p4  const PortId_t PORT_PGEN/PORT_L : PORT_L    = 9w8
PORT_PGEN = 68   # .p4  const PortId_t PORT_PGEN = 9w68

QID_ABLOCK = 7   # .p4  const bit<5> QID_ABLOCK = 5w7
QID_ACK = 6      # .p4  const bit<5> QID_ACK    = 5w6
QID_RBLOCK = 5   # .p4  const bit<5> QID_RBLOCK = 5w5
QID_RESP = 4     # .p4  const bit<5> QID_RESP   = 5w4

# role byte values stamped by the enqueue actions (.p4 ROLE_* constants)
ROLE_ID = {"ABLOCK": 1, "ACK": 2, "RBLOCK": 3, "RESP": 4}
ROLE_NAME = dict((v, k) for k, v in ROLE_ID.items())

# canonical role order + the qid each role is parked on + its enqueue action
ROLES = [
    ("ABLOCK", QID_ABLOCK, "Ingress.enq_ablock"),
    ("ACK", QID_ACK, "Ingress.enq_ack"),
    ("RBLOCK", QID_RBLOCK, "Ingress.enq_rblock"),
    ("RESP", QID_RESP, "Ingress.enq_resp"),
]

N_PACKETS = 128           # one batch (.p4 header: 32 per role)
N_PER_ROLE = 32
TRACE_LEN = 512           # .p4  const int TRACE_LEN = 512

# ---- the THREE per-trial accounting registers ------------------------------
# .p4  Register reg_total_dequeues / reg_written / reg_overflow. They are
# Registers rather than Counter slots on purpose: a Register reads live over
# bfrt, while a Stats-ALU Counter returns a stale 0 unless SyncCounters is run
# first. The cleanup path polls these, so they must be trustworthy on every
# read without an extra operation.
REG_TOTAL = "reg_total_dequeues"
REG_WRITTEN = "reg_written"
REG_OVERFLOW = "reg_overflow"
TRIAL_REGS = (REG_TOTAL, REG_WRITTEN, REG_OVERFLOW)

# The JSON key each register is reported under. The analyzer reads these names.
REG_JSON_KEY = {
    REG_TOTAL: "total_dequeues",
    REG_WRITTEN: "trace_entries_written",
    REG_OVERFLOW: "trace_overflow",
}

# ---- the five priority modes -----------------------------------------------
# Values are tf1.tm.queue.sched_cfg max_priority strings. The schema's choices
# are ['LOW','0','1','2','3','4','5','6','7','HIGH'] (bf_rt_tm_tf1.json), so the
# numeric ladder 7/6/5/4 is directly expressible.
#
#   ladder   the INTENDED configuration under test
#   reversed the strongest control: same role->qid map, priorities reversed. If
#            the observed order reverses too, the trace provably tracks the
#            scheduler and not the emission order or the qid numbering.
#   equal    the DWRR control: no priority difference at all
#   tied     ABLOCK and ACK tied ABOVE RBLOCK above RESP
#   custom   whatever --priority says
PRIORITY_MODES = {
    "ladder":   {"ABLOCK": "7", "ACK": "6", "RBLOCK": "5", "RESP": "4"},
    "reversed": {"ABLOCK": "4", "ACK": "5", "RBLOCK": "6", "RESP": "7"},
    "equal":    {"ABLOCK": "4", "ACK": "4", "RBLOCK": "4", "RESP": "4"},
    "tied":     {"ABLOCK": "6", "ACK": "6", "RBLOCK": "5", "RESP": "4"},
}

# ---- bfrt table names (all from the 9.13.1 fixed-function schemas) ----------
TM_PORT_CFG = "tf1.tm.port.cfg"                  # KEY dev_port
TM_SCHED_CFG = "tf1.tm.queue.sched_cfg"          # KEY pg_id, pg_queue
TM_QUEUE_MAP = "tf1.tm.queue.map"                # KEY pg_id, pg_queue
TM_COUNTER_QUEUE = "tf1.tm.counter.queue"        # KEY pg_id, pg_queue
TM_PORT_SHAPING = "tf1.tm.port.sched_shaping"    # KEY dev_port
TM_PORT_SCHED_CFG = "tf1.tm.port.sched_cfg"      # KEY dev_port
PKTGEN_PORT_CFG = "tf1.pktgen.port_cfg"          # KEY dev_port
PKTGEN_PKT_BUFFER = "tf1.pktgen.pkt_buffer"      # KEY offset, size
PKTGEN_APP_CFG = "tf1.pktgen.app_cfg"            # KEY app_id (ACTION-based)

CTR_FIELDS = ("usage_cells", "watermark_cells", "drop_count_packets")

# P4 counter slot indices (.p4 C_* constants)
CTR_SLOTS = [
    (0, "drop_bad_port"), (1, "drop_non_oracle"),
    (2, "enq_ablock"), (3, "enq_ack"), (4, "enq_rblock"), (5, "enq_resp"),
    (6, "drop_bad_id"), (7, "traced"), (8, "trace_overflow"),
]

# ---- dp8's ORIGINAL scheduling state, restored by --restore-dp8 -------------
DP8_ORIGINAL = {
    "max_rate_enable": False,
    "max_rate": 25010000,
    "unit": "BPS",
    "max_burst_size": 9216,
    "scheduling_speed": "BF_SPEED_25G",
}

# ---- the generated frame template ------------------------------------------
# 64 bytes. The hardware PREPENDS its own 6-byte generator header, which the P4
# extracts and never emits, so what reaches the queue is exactly these 64 bytes
# with oracle.role and oracle.pkt_id stamped in. Locally-administered MACs; this
# frame never leaves the chip.
TPL_DST = bytes([0x02, 0x00, 0x00, 0x00, 0x88, 0xC3])
TPL_SRC = bytes([0x02, 0x00, 0x00, 0x00, 0x88, 0xC4])
TPL_ETYPE = 0x88C3        # .p4  const bit<16> ETHERTYPE_ORACLE4 = 0x88C3
TPL_LEN = 64


def build_template(trial_id):
    """The 64-byte packet-buffer template for one trial.

    Layout mirrors headers_t in the .p4 exactly:
        [0:6]   eth.dst
        [6:12]  eth.src
        [12:14] eth.etype   = 0x88C3
        [14:16] oracle.trial_id   <- the only per-trial field
        [16]    oracle.role       = 0, stamped by the enqueue action
        [17:19] oracle.pkt_id     = 0, stamped by the enqueue action
        [19:64] pad, never extracted, re-emitted verbatim by the deparser
    """
    b = bytearray(TPL_LEN)
    b[0:6] = TPL_DST
    b[6:12] = TPL_SRC
    b[12] = (TPL_ETYPE >> 8) & 0xFF
    b[13] = TPL_ETYPE & 0xFF
    b[14] = (trial_id >> 8) & 0xFF
    b[15] = trial_id & 0xFF
    # role and pkt_id stay zero; ingress stamps them.
    return bytes(b)


class DirtyStateError(Exception):
    """A trial refused to start because the switch was not in a clean state.

    This is deliberately an EXCEPTION and not a return code. The five-control
    pilot's whole failure was that control A ended without releasing, left 124
    packets backlogged, and control B1 then drained A's leftovers together with
    its own batch (a traced delta of 252). Nothing downstream of a dirty start
    is interpretable, so the trial must not proceed at all.
    """


def _i(v):
    """None-preserving int()."""
    return None if v is None else int(v)


def pnorm(v):
    """Normalize a sched_cfg priority ('LOW'|'0'..'7'|'HIGH') to an int."""
    if v is None:
        return None
    s = str(v).upper()
    if s == "HIGH":
        return 7
    if s == "LOW":
        return 0
    try:
        return int(s)
    except ValueError:
        return None


class Checks(object):
    """PASS / WARN / FAIL accumulator. Nothing proceeds silently past a mismatch."""

    def __init__(self):
        self.rows = []
        self.n_fail = 0

    def ok(self, name, detail=""):
        self.rows.append(("PASS", name, str(detail)))

    def warn(self, name, detail=""):
        self.rows.append(("WARN", name, str(detail)))

    def fail(self, name, detail=""):
        self.rows.append(("FAIL", name, str(detail)))
        self.n_fail += 1

    def expect(self, name, got, want, extra=""):
        if got == want:
            self.ok(name, ("%s %s" % (got, extra)).strip())
        else:
            self.fail(name, ("got %r, expected %r %s" % (got, want, extra)).strip())

    def render(self):
        if not self.rows:
            return "\n(no checks run)"
        w = max([len(r[1]) for r in self.rows] + [5])
        lines = ["", "%-4s  %-*s  %s" % ("RES", w, "CHECK", "DETAIL"),
                 "%-4s  %-*s  %s" % ("-" * 4, w, "-" * w, "-" * 40)]
        for res, name, detail in self.rows:
            lines.append("%-4s  %-*s  %s" % (res, w, name, detail))
        n_pass = len([r for r in self.rows if r[0] == "PASS"])
        n_warn = len([r for r in self.rows if r[0] == "WARN"])
        lines += ["", "%d check(s): %d PASS, %d WARN, %d FAIL"
                  % (len(self.rows), n_pass, n_warn, self.n_fail)]
        return "\n".join(lines)


# ===========================================================================
# gRPC helpers
# ===========================================================================
def get_entry(tbl, tgt, keyfields, from_hw=True):
    """entry_get one key -> (data dict, None) or (None, error string)."""
    import bfrt_grpc.client as gc
    try:
        key = tbl.make_key([gc.KeyTuple(k, v) for k, v in keyfields])
    except Exception as e:
        return None, "make_key: %s" % str(e)[:90]
    try:
        got = None
        for d, _k in tbl.entry_get(tgt, [key], {"from_hw": from_hw}):
            got = d.to_dict()
        return (got, None) if got is not None else (None, "entry does not exist")
    except Exception as e:
        return None, "entry_get: %s" % str(e)[:90]


def get_table(bi, name, chk=None):
    """Resolve a bfrt table, tolerant of the pipeline prefix.

    P4 objects resolve as 'pipe.Ingress.<name>' on this SDE, but the prefix has
    differed between builds, so candidates are tried in order and a name scan is
    the last resort. Carried from ibspg_trace_read2.py:63, which is the reader
    that produced the two-queue result.
    """
    for cand in ("pipe.Ingress." + name, "Ingress." + name, name):
        try:
            return bi.table_get(cand)
        except Exception:
            continue
    try:
        for tn in bi.table_dict.keys():
            if tn.endswith("." + name) or tn.endswith("Ingress." + name):
                return bi.table_get(tn)
    except Exception:
        pass
    if chk is not None:
        chk.fail("table lookup '%s'" % name, "not found in bfrt info")
    return None


def _flatten_max(vals):
    """Collapse a register readback to one int.

    A Register read returns one value per pipe (and per SALU half), so the raw
    result is a list, sometimes nested. The oracle only ever writes from pipe 0,
    so every other element is the initial 0 and the maximum is the written value.
    Carried from ibspg_trace_read2.py:48.
    """
    ints = []
    stack = list(vals)
    while stack:
        v = stack.pop()
        if isinstance(v, (list, tuple)):
            stack.extend(v)
        elif isinstance(v, bool):
            ints.append(int(v))
        elif isinstance(v, int):
            ints.append(v)
    return max(ints) if ints else None


def _reg_value_from(dd):
    """Pull the single data value out of a register entry dict."""
    vals = []
    for kk, vv in dd.items():
        if kk == "$REGISTER_INDEX" or kk == "action_name" or kk.startswith("is_"):
            continue
        vals.append(vv)
    return _flatten_max(vals)


def reg_read(bi, tgt, name, idx, chk=None):
    """Read Register <name> at one index."""
    import bfrt_grpc.client as gc
    t = get_table(bi, name, chk)
    if t is None:
        return None
    k = t.make_key([gc.KeyTuple("$REGISTER_INDEX", idx)])
    try:
        for d, _ in t.entry_get(tgt, [k], {"from_hw": True}):
            return _reg_value_from(d.to_dict())
    except Exception as e:
        if chk is not None:
            chk.fail("reg_read %s[%d]" % (name, idx), str(e)[:90])
    return None


def reg_read_range(bi, tgt, name, n, chk=None):
    """Read Register <name> over indices 0..n-1, batched into ONE entry_get.

    The response is mapped back to an index using the $REGISTER_INDEX that the
    SDE echoes in the data dict, so response ORDER is never assumed. If the batch
    path fails for any reason the reader falls back to n single reads, which is
    slower but cannot be wrong.

    TODO(silicon): whether this SDE echoes $REGISTER_INDEX in the data dict is
    the one unverified assumption. RESOLVING CHECK: --trace-dump reports
    `index_source` as 'echoed' or 'fallback-perindex'; if it says 'fallback',
    the batch path was not usable and the per-index path produced the trace.
    """
    import bfrt_grpc.client as gc
    t = get_table(bi, name, chk)
    if t is None:
        return [None] * n, "table-missing"
    keys = [t.make_key([gc.KeyTuple("$REGISTER_INDEX", i)]) for i in range(n)]
    out = [None] * n
    try:
        seen = 0
        for d, k in t.entry_get(tgt, keys, {"from_hw": True}):
            dd = d.to_dict()
            idx = dd.get("$REGISTER_INDEX")
            if idx is None:
                try:
                    idx = k.to_dict()["$REGISTER_INDEX"]["value"]
                except Exception:
                    idx = None
            if idx is None:
                raise RuntimeError("no $REGISTER_INDEX echoed")
            idx = int(idx)
            if 0 <= idx < n:
                out[idx] = _reg_value_from(dd)
                seen += 1
        if seen == n:
            return out, "echoed"
    except Exception:
        pass
    # fallback: one read per index
    for i in range(n):
        out[i] = reg_read(bi, tgt, name, i, chk)
    return out, "fallback-perindex"


def ctr_read(bi, tgt, name, idx, chk=None):
    """Read PACKETS Counter <name> at <idx>.

    A Stats-ALU counter needs an explicit HW->SW sync before a control-plane
    read; from_hw alone returns a stale 0. Carried from ibspg_trace_read2.py:100.
    """
    import bfrt_grpc.client as gc
    t = get_table(bi, name, chk)
    if t is None:
        return None
    try:
        t.operations_execute(tgt, "SyncCounters")
    except Exception:
        pass
    k = t.make_key([gc.KeyTuple("$COUNTER_INDEX", idx)])
    vals = []
    try:
        for d, _ in t.entry_get(tgt, [k], {"from_hw": True}):
            dd = d.to_dict()
            if "$COUNTER_SPEC_PKTS" in dd:
                vals.append(dd["$COUNTER_SPEC_PKTS"])
    except Exception as e:
        if chk is not None:
            chk.warn("ctr_read %s[%d]" % (name, idx), str(e)[:80])
        return None
    return int(_flatten_max(vals) or 0)


def reg_zero(bi, tgt, name, idx, chk):
    """Write 0 into Register <name> at <idx>.

    The data field name is DISCOVERED from a read rather than guessed: it
    resolves as something like 'Ingress.<name>.f1' and the exact spelling has
    varied between builds.
    """
    import bfrt_grpc.client as gc
    t = get_table(bi, name, chk)
    if t is None:
        return False
    k = t.make_key([gc.KeyTuple("$REGISTER_INDEX", idx)])
    field = None
    try:
        for d, _ in t.entry_get(tgt, [k], {"from_hw": True}):
            for kk in d.to_dict():
                if kk == "$REGISTER_INDEX" or kk == "action_name" or kk.startswith("is_"):
                    continue
                field = kk
                break
    except Exception as e:
        chk.fail("reg_zero %s[%d] discover field" % (name, idx), str(e)[:80])
        return False
    if field is None:
        chk.fail("reg_zero %s[%d]" % (name, idx), "no data field found in readback")
        return False
    try:
        t.entry_mod(tgt, [k], [t.make_data([gc.DataTuple(field, 0)])])
        return True
    except Exception as e:
        chk.fail("reg_zero %s[%d] write" % (name, idx), str(e)[:80])
        return False


def ctr_zero(bi, tgt, name, idx, chk=None):
    """Write 0 into PACKETS Counter <name> at <idx>.

    TODO(silicon): whether this SDE accepts a write to $COUNTER_SPEC_PKTS on an
    indirect P4 counter is unverified off-switch. RESOLVING CHECK: the
    "P4 counters cleared" row in the cleanup record — it reports the count of
    slots that accepted the write, and a WARN naming the first that did not.
    This is NOT load-bearing: the three accounting REGISTERS are what the clean
    -start assertion tests, and the sweep reports enq_* as before/after DELTAS,
    so an uncleanable counter degrades the evidence rather than invalidating it.
    """
    import bfrt_grpc.client as gc
    t = get_table(bi, name, chk)
    if t is None:
        return False
    try:
        k = t.make_key([gc.KeyTuple("$COUNTER_INDEX", idx)])
        t.entry_mod(tgt, [k], [t.make_data([gc.DataTuple("$COUNTER_SPEC_PKTS", 0)])])
        return True
    except Exception:
        return False


# ===========================================================================
# 1. Port-group resolution and the four queues
# ===========================================================================
_PG_CACHE = {}


def resolve_pg_quiet(bi, tgt0, dev_port):
    """(pg_id, pg_port_nr) with no printing and no PASS/FAIL rows, cached.

    resolve_pg() below is the loud version used once per phase. This one exists
    because the drain poll calls it in a loop, and a check row per poll would
    bury the checks that matter.
    """
    if dev_port in _PG_CACHE:
        return _PG_CACHE[dev_port]
    pcfg = get_table(bi, TM_PORT_CFG)
    if pcfg is None:
        return None, None
    got, err = get_entry(pcfg, tgt0, [("dev_port", dev_port)])
    if err or got is None:
        return None, None
    val = (got.get("pg_id"), got.get("pg_port_nr"))
    _PG_CACHE[dev_port] = val
    return val


def resolve_pg(bi, tgt0, dev_port, chk, out):
    """READ the (pg_id, pg_port_nr) of a dev_port instead of guessing it."""
    pcfg = get_table(bi, TM_PORT_CFG, chk)
    if pcfg is None:
        return None, None
    got, err = get_entry(pcfg, tgt0, [("dev_port", dev_port)])
    if err:
        chk.fail("%s dp%d" % (TM_PORT_CFG, dev_port), err)
        return None, None
    pg_id, pg_nr = got.get("pg_id"), got.get("pg_port_nr")
    out.setdefault("port_cfg", {})["dp%d" % dev_port] = {
        "pg_id": pg_id, "pg_port_nr": pg_nr,
        "port_queues_count": got.get("port_queues_count")}
    chk.ok("dp%d port-group map (read, not guessed)" % dev_port,
           "pg_id=%s pg_port_nr=%s" % (pg_id, pg_nr))
    return pg_id, pg_nr


def pg_queue_of(pg_nr, qid):
    """pg_queue = pg_port_nr * 8 + qid (TF1: 8 queues per port in a port group)."""
    return pg_nr * 8 + qid


def priority_map(a):
    """The wanted max_priority per role for the selected mode."""
    if a.priority_mode == "custom":
        m = {}
        for item in (a.priority or "").split(","):
            item = item.strip()
            if not item:
                continue
            k, _sep, v = item.partition("=")
            m[k.strip().upper()] = v.strip()
        return m
    return dict(PRIORITY_MODES[a.priority_mode])


def config_ports(bi, tgt, a, out, chk):
    """dp8 MAC-near loopback. dp11 is NOT configured and Hulk is NOT involved."""
    import bfrt_grpc.client as gc
    port_tbl = bi.table_get("$PORT")
    try:
        lk = [port_tbl.make_key([gc.KeyTuple("$DEV_PORT", a.port_l)])]
        try:
            port_tbl.entry_del(tgt, lk)   # a live entry rejects a mode change
        except Exception:
            pass
        port_tbl.entry_add(tgt, lk, [port_tbl.make_data([
            gc.DataTuple("$SPEED", str_val="BF_SPEED_25G"),
            gc.DataTuple("$FEC", str_val="BF_FEC_TYP_NONE"),
            gc.DataTuple("$AUTO_NEGOTIATION", str_val="PM_AN_FORCE_DISABLE"),
            gc.DataTuple("$LOOPBACK_MODE", str_val="BF_LPBK_MAC_NEAR"),
            gc.DataTuple("$PORT_ENABLE", bool_val=True)])])
        chk.ok("dp%d MAC-near loopback" % a.port_l, "BF_LPBK_MAC_NEAR 25G")
    except Exception as e:
        chk.fail("dp%d MAC-near loopback" % a.port_l, str(e)[:90])
    out["ports_configured"] = [a.port_l]
    chk.ok("dp11 NOT configured", "this oracle has no host port by construction")


def write_priorities(bi, tgt0, a, out, chk, write=True):
    """Write and read back max_priority on the four dp8 queues.

    max_priority arbitrates among BACKLOGGED queues in the remaining-bandwidth
    pass. min_priority orders only the guaranteed pass and is INERT unless
    min_rate_enable is true — setting it instead of max_priority is precisely the
    silent configuration error the IBSPG root-cause repair found, so it is left
    alone here and max_rate/min_rate enables are forced off separately.
    """
    import bfrt_grpc.client as gc
    want = priority_map(a)
    out["priority_mode"] = a.priority_mode
    out["priority_want"] = want

    pg_id, pg_nr = resolve_pg(bi, tgt0, a.port_l, chk, out)
    if pg_id is None:
        chk.fail("priorities", "could not resolve dp%d pg map" % a.port_l)
        return
    q_cfg = get_table(bi, TM_SCHED_CFG, chk)
    if q_cfg is None:
        return
    q_map = get_table(bi, TM_QUEUE_MAP)

    got_map = {}
    for role, qid, _act in ROLES:
        pgq = pg_queue_of(pg_nr, qid)
        key = q_cfg.make_key([gc.KeyTuple("pg_id", pg_id), gc.KeyTuple("pg_queue", pgq)])
        if write:
            w = want.get(role)
            if w is None:
                chk.fail("%s priority" % role, "no value for this role in mode %s"
                         % a.priority_mode)
                continue
            try:
                q_cfg.entry_mod(tgt0, [key], [q_cfg.make_data([
                    gc.DataTuple("scheduling_enable", bool_val=True),
                    gc.DataTuple("max_rate_enable", bool_val=False),
                    gc.DataTuple("min_rate_enable", bool_val=False),
                    gc.DataTuple("max_priority", str_val=str(w))])])
            except Exception as e:
                chk.fail("%s max_priority write" % role, str(e)[:90])
                continue
        sc, err = get_entry(q_cfg, tgt0, [("pg_id", pg_id), ("pg_queue", pgq)])
        if err:
            chk.fail("%s sched_cfg readback" % role, err)
            continue
        dev_port = None
        if q_map is not None:
            qm, qerr = get_entry(q_map, tgt0, [("pg_id", pg_id), ("pg_queue", pgq)])
            if not qerr:
                dev_port = (qm or {}).get("dev_port")
        rec = {"qid": qid, "pg_queue": pgq,
               "max_priority": sc.get("max_priority"),
               "min_priority": sc.get("min_priority"),
               "scheduling_enable": sc.get("scheduling_enable"),
               "max_rate_enable": sc.get("max_rate_enable"),
               "min_rate_enable": sc.get("min_rate_enable"),
               "dwrr_weight": sc.get("dwrr_weight"),
               "dev_port": dev_port}
        out.setdefault("queues", {})[role] = rec
        got_map[role] = pnorm(rec["max_priority"])
        if write:
            chk.expect("%s max_priority" % role, pnorm(rec["max_priority"]),
                       pnorm(want.get(role)), "(qid %d, pg_queue %d)" % (qid, pgq))
        # A queue that is over its own max rate goes shaping-INELIGIBLE and the
        # TM serves a lower-priority eligible queue. That is not a priority
        # violation but it is indistinguishable from one, so it is asserted off.
        chk.expect("%s per-queue max_rate_enable is False" % role,
                   rec["max_rate_enable"], False)
        if dev_port is not None and int(dev_port) != a.port_l:
            chk.fail("%s maps to dp%d" % (role, a.port_l),
                     "queue.map reports dev_port=%s" % dev_port)

    out["priority_got"] = got_map
    print("")
    print("dp8 queue priorities (mode=%s)  [%s]" % (a.priority_mode, TM_SCHED_CFG))
    print("  %-8s %4s %10s %10s %10s %10s" % ("role", "qid", "want", "got",
                                              "sched_en", "max_rate_en"))
    for role, qid, _a in ROLES:
        r = out.get("queues", {}).get(role, {})
        print("  %-8s %4d %10s %10s %10s %10s"
              % (role, qid, want.get(role), r.get("max_priority"),
                 r.get("scheduling_enable"), r.get("max_rate_enable")))
    print("")
    # This readback is CONFIGURATION EVIDENCE ONLY. It says what was written.
    chk.warn("readback is not the proof",
             "max_priority readback shows what was WRITTEN. The behavioural "
             "verdict comes from the on-chip dequeue trace, via "
             "analysis/analyze_four_queue_dequeue.py")


# ===========================================================================
# 2. THE ROLE MAP — where the per-trial randomization lives
# ===========================================================================
def build_role_map(seed):
    """packet_id -> role name, exactly N_PER_ROLE of each, shuffled by `seed`.

    The multiset is FIXED (32 of each) and only the assignment is permuted, so
    every trial has identical queue backlogs and differs only in which generated
    packet goes where. Emission order is hardware-fixed at 0,1,...,127, so a
    dequeue order that tracks ROLE rather than packet_id cannot be an artifact of
    emission order.
    """
    pool = []
    for role, _qid, _act in ROLES:
        pool.extend([role] * N_PER_ROLE)
    random.Random(seed).shuffle(pool)
    return pool


def write_role_map(bi, tgt, a, out, chk, mapping):
    """Write all 128 tbl_role entries.

    Batched: one entry_add for all 128 keys, falling back to entry_mod when the
    entries already exist from a previous trial. Two RPCs at worst.

    TODO(silicon): whether this SDE accepts 128 keys in a single entry_add /
    entry_mod is unverified off-switch (the proven batched writes in this project
    are 4-entry TM writes). RESOLVING CHECK: the "tbl_role: 128 entries" row. If
    the batch is rejected, the failure detail carries the gRPC error and the loop
    can be changed to one RPC per entry — 128 RPCs is slow but has no effect on
    the measurement, because the map is fully written BEFORE the gate is closed
    and before any packet is generated.
    """
    import bfrt_grpc.client as gc
    t = get_table(bi, "tbl_role", chk)
    if t is None:
        return
    act_of = dict((role, act) for role, _q, act in ROLES)
    keys, datas = [], []
    for pid, role in enumerate(mapping):
        keys.append(t.make_key([gc.KeyTuple("hdr.pgen.packet_id", pid)]))
        datas.append(t.make_data([], act_of[role]))
    added = None
    try:
        t.entry_add(tgt, keys, datas)
        added = "entry_add"
    except Exception:
        try:
            t.entry_mod(tgt, keys, datas)
            added = "entry_mod"
        except Exception as e:
            chk.fail("tbl_role write (128 entries)", str(e)[:90])
            return
    counts = {}
    for r in mapping:
        counts[r] = counts.get(r, 0) + 1
    out["role_map"] = {"seed": a.seed, "path": added, "counts": counts,
                       "mapping": mapping}
    ok = all(counts.get(r) == N_PER_ROLE for r, _q, _a in ROLES)
    if ok:
        chk.ok("tbl_role: %d entries, %d per role" % (len(mapping), N_PER_ROLE),
               "%s, seed=%s" % (added, a.seed))
    else:
        chk.fail("tbl_role role balance", "counts=%s (want %d each)" % (counts, N_PER_ROLE))


# ===========================================================================
# 3. THE GLOBAL RELEASE GATE — a PORT-level max-rate shaper on dp8
# ===========================================================================
def _port_entry(tbl, tgts, dev_port):
    """entry_get for a dev_port-keyed table, trying each target in turn."""
    last = "no target tried"
    for tname, tgt in tgts:
        got, err = get_entry(tbl, tgt, [("dev_port", dev_port)])
        if not err:
            return got, None, tname
        last = err
    return None, last, None


def read_port_gate(bi, tgts, a, out, chk, label="gate"):
    """Read both gate tables for the gate port. Never writes."""
    shp = get_table(bi, TM_PORT_SHAPING, chk)
    cfg = get_table(bi, TM_PORT_SCHED_CFG, chk)
    rec = {"dev_port": a.gate_port}
    if shp is not None:
        got, err, tname = _port_entry(shp, tgts, a.gate_port)
        rec["sched_shaping"] = got if not err else {"err": err}
        rec["shaping_target"] = tname
    if cfg is not None:
        got, err, tname = _port_entry(cfg, tgts, a.gate_port)
        rec["sched_cfg"] = got if not err else {"err": err}
        rec["cfg_target"] = tname
    out.setdefault("port_gate", {})[label] = rec
    sh = rec.get("sched_shaping") or {}
    sc = rec.get("sched_cfg") or {}
    rec["armed"] = sc.get("max_rate_enable")
    print("port gate dp%d [%s]: max_rate_enable=%s unit=%s prov=%s max_rate=%s "
          "burst=%s speed=%s"
          % (a.gate_port, label, rec["armed"], sh.get("unit"), sh.get("provisioning"),
             sh.get("max_rate"), sh.get("max_burst_size"), sc.get("scheduling_speed")))
    return rec


def guard_gate_port(a, chk):
    """Refuse to gate a port that does not own the four queues.

    The queues under test live on dp8. A gate on any other port would hold
    traffic the dp8 scheduler had ALREADY ordered, and would pass meaninglessly.
    That is a silent-success failure mode, so it is refused, not warned about.
    """
    if a.gate_port == a.port_l:
        return True
    if a.i_know_the_gate_port_is_wrong:
        chk.warn("gate port override",
                 "gating dp%d, which does NOT own the four queues (dp%d). "
                 "Results are NOT a strict-priority verdict." % (a.gate_port, a.port_l))
        return True
    chk.fail("gate port owns the four queues",
             "--gate-port dp%d does not own the four queues (dp%d = PORT_L). "
             "Pass --i-know-the-gate-port-is-wrong to override."
             % (a.gate_port, a.port_l))
    return False


def set_port_gate(bi, tgts, a, closed, out, chk):
    """CLOSE (2 writes: shape, then arm) or OPEN (exactly ONE write).

    OPEN prefers max_rate_enable=False (disarm) over raising max_rate: disarming
    takes the token bucket OUT of the path, so the release boundary cannot depend
    on the bucket's banked credit or deficit state.
    """
    import bfrt_grpc.client as gc
    if not guard_gate_port(a, chk):
        return
    shp = get_table(bi, TM_PORT_SHAPING, chk)
    cfg = get_table(bi, TM_PORT_SCHED_CFG, chk)
    if shp is None or cfg is None:
        return

    def _mod(tbl, tuples, what):
        last = "no target tried"
        for tname, tgt in tgts:
            try:
                key = tbl.make_key([gc.KeyTuple("dev_port", a.gate_port)])
                tbl.entry_mod(tgt, [key], [tbl.make_data(tuples)])
                return tname, None
            except Exception as e:
                last = str(e)[:90]
        chk.fail(what, last)
        return None, last

    if closed:
        t0 = time.time()
        _tn1, e1 = _mod(shp, [
            gc.DataTuple("unit", str_val=a.gate_unit),
            gc.DataTuple("provisioning", str_val=a.gate_provisioning),
            gc.DataTuple("max_rate", int(a.gate_rate)),
            gc.DataTuple("max_burst_size", int(a.gate_burst))],
            "gate close: shaping params")
        _tn2, e2 = _mod(cfg, [gc.DataTuple("max_rate_enable", bool_val=True)],
                        "gate close: arm max_rate_enable")
        dt = time.time() - t0
        out["gate_close"] = {"dev_port": a.gate_port, "unit": a.gate_unit,
                             "max_rate": a.gate_rate, "max_burst_size": a.gate_burst,
                             "seconds": round(dt, 6), "n_writes": 2}
        if not e1 and not e2:
            chk.ok("gate CLOSED on dp%d" % a.gate_port,
                   "%s max_rate=%d burst=%d armed (%.2f ms, 2 writes)"
                   % (a.gate_unit, a.gate_rate, a.gate_burst, dt * 1e3))
    else:
        t0 = time.time()
        tn, err = _mod(cfg, [gc.DataTuple("max_rate_enable", bool_val=False)],
                       "gate open: disarm max_rate_enable")
        dt = time.time() - t0
        out["gate_open"] = {"dev_port": a.gate_port, "n_writes": 1,
                            "detail": "%s max_rate_enable=False" % TM_PORT_SCHED_CFG,
                            "seconds": round(dt, 6), "target": tn,
                            "release_write_unix": time.time()}
        if not err:
            chk.ok("gate OPENED on dp%d — ONE write" % a.gate_port,
                   "%s max_rate_enable=False (%.2f ms)" % (TM_PORT_SCHED_CFG, dt * 1e3))

    rb = read_port_gate(bi, tgts, a, out, chk,
                        label="after_close" if closed else "after_open")
    if closed:
        chk.expect("gate armed after close", rb.get("armed"), True)
        sh = rb.get("sched_shaping") or {}
        # A silently clamped burst is a STOP: banked burst credit is the main
        # threat to a clean release boundary.
        if sh.get("max_rate") is not None and int(sh["max_rate"]) != int(a.gate_rate):
            chk.fail("gate max_rate readback",
                     "wrote %d, read %s — the SDE quantized or rejected the rate"
                     % (a.gate_rate, sh.get("max_rate")))
        if (sh.get("max_burst_size") is not None
                and int(sh["max_burst_size"]) != int(a.gate_burst)):
            chk.fail("gate max_burst_size readback",
                     "wrote %d, read %s — a clamped burst banks credit that escapes "
                     "before the release" % (a.gate_burst, sh.get("max_burst_size")))
    else:
        chk.expect("gate disarmed after open", rb.get("armed"), False)


def restore_dp8(bi, tgts, a, out, chk):
    """Put dp8's scheduling configuration back to its ORIGINAL state."""
    import bfrt_grpc.client as gc
    shp = get_table(bi, TM_PORT_SHAPING, chk)
    cfg = get_table(bi, TM_PORT_SCHED_CFG, chk)
    if shp is None or cfg is None:
        return
    o = DP8_ORIGINAL

    def _mod(tbl, tuples, what):
        last = "no target tried"
        for tname, tgt in tgts:
            try:
                key = tbl.make_key([gc.KeyTuple("dev_port", a.port_l)])
                tbl.entry_mod(tgt, [key], [tbl.make_data(tuples)])
                return True
            except Exception as e:
                last = str(e)[:90]
        chk.fail(what, last)
        return False

    _mod(shp, [gc.DataTuple("unit", str_val=o["unit"]),
               gc.DataTuple("provisioning", str_val="UPPER"),
               gc.DataTuple("max_rate", int(o["max_rate"])),
               gc.DataTuple("max_burst_size", int(o["max_burst_size"]))],
         "restore dp8 shaping")
    _mod(cfg, [gc.DataTuple("max_rate_enable", bool_val=o["max_rate_enable"]),
               gc.DataTuple("scheduling_speed", str_val=o["scheduling_speed"])],
         "restore dp8 sched_cfg")

    rb = read_port_gate(bi, tgts, a, out, chk, label="after_restore")
    sh = rb.get("sched_shaping") or {}
    sc = rb.get("sched_cfg") or {}
    chk.expect("dp8 max_rate_enable restored", sc.get("max_rate_enable"),
               o["max_rate_enable"])
    chk.expect("dp8 max_rate restored",
               None if sh.get("max_rate") is None else int(sh["max_rate"]),
               o["max_rate"])
    chk.expect("dp8 unit restored", sh.get("unit"), o["unit"])
    chk.expect("dp8 max_burst_size restored",
               None if sh.get("max_burst_size") is None else int(sh["max_burst_size"]),
               o["max_burst_size"])
    chk.expect("dp8 scheduling_speed restored", sc.get("scheduling_speed"),
               o["scheduling_speed"])
    out["dp8_restored"] = True


# ===========================================================================
# 4. Packet generator
# ===========================================================================
def config_pktgen(bi, tgts, a, out, chk, template=None):
    """Configure the generator: port, buffer template, one-shot timer app.

    Sequence and field names from the SDE's own example,
    pkgsrc/p4-examples/p4_16_programs/tna_pktgen/test.py (the timer_one_shot
    case), and the schema install/share/bf_rt_shared/bf_rt_pktgen_tf1.json.

    The app is left DISABLED. Enabling it starts the countdown and fires the
    batch, which is what fire_pktgen() does per trial.
    """
    import bfrt_grpc.client as gc
    if template is None:
        template = build_template(a.trial_id)

    # --- (1) port_cfg: run the generator on dp68 ---------------------------
    # A one-shot TIMER app needs only pktgen_enable. recirculation_enable and
    # pattern_matching_enable are for recirc-PATTERN triggers; they are read back
    # and reported but deliberately not written, so nothing else on dp68 is
    # disturbed.
    #
    # TODO(silicon): this is the SDE example's timer sequence
    # (pkgsrc/p4-examples/p4_16_programs/tna_pktgen/test.py, which sets ONLY
    # pktgen_enable for the timer app), but every previous pktgen run on THIS
    # switch used a recirc-PATTERN trigger, which additionally needs
    # recirculation_enable and pattern_matching_enable. Whether a timer app is
    # happy with pktgen_enable alone here is therefore not yet observed.
    # RESOLVING CHECK: the "pktgen pkt_counter" row after fire_pktgen(). It reads
    # 128 if the app fires. If it reads 0, add recirculation_enable=True (and
    # then pattern_matching_enable=True) to the write below and re-run.
    pcfg = get_table(bi, PKTGEN_PORT_CFG, chk)
    if pcfg is not None:
        okp = False
        for _tn, tgt in tgts:
            try:
                pcfg.entry_mod(tgt,
                               [pcfg.make_key([gc.KeyTuple("dev_port", a.port_pgen)])],
                               [pcfg.make_data([gc.DataTuple("pktgen_enable",
                                                             bool_val=True)])])
                okp = True
                break
            except Exception:
                continue
        got, err, _t = _port_entry(pcfg, tgts, a.port_pgen)
        out["pktgen_port_cfg"] = got if not err else {"err": err}
        if okp and not err and got.get("pktgen_enable"):
            chk.ok("pktgen enabled on dp%d" % a.port_pgen, str(got))
        else:
            chk.fail("pktgen enabled on dp%d" % a.port_pgen,
                     "write_ok=%s readback=%s" % (okp, got if not err else err))

    # --- (2) pkt_buffer: the 64-byte template ------------------------------
    # The buffer holds ONLY what follows the 6-byte generator header, which the
    # hardware prepends; the P4 extracts and never emits it, so what reaches the
    # queue is exactly these bytes. Offset must be 16-byte aligned.
    #
    # TODO(silicon): that pkt_len counts BUFFER bytes and excludes the 6-byte
    # generator header is read off the SDE example, where a 100-byte buffer is
    # written with pkt_len=100 and the P4 extracts a 6-byte pgen header before
    # Ethernet, and the test then verifies the received packet equals the
    # 100-byte buffer exactly. It has not been measured here.
    # RESOLVING CHECK: the P4 counters after a trial. If the offset assumption is
    # wrong the ethertype does not land at byte 12 of the post-header frame, the
    # parser's 0x88C3 test fails, and every packet lands on drop_non_oracle
    # instead of the enq_* slots. So: drop_non_oracle == 0 and
    # enq_ablock+enq_ack+enq_rblock+enq_resp == 128 confirms the layout.
    pbuf = get_table(bi, PKTGEN_PKT_BUFFER, chk)
    if pbuf is not None:
        wrote = False
        for _tn, tgt in tgts:
            try:
                pbuf.entry_mod(
                    tgt,
                    [pbuf.make_key([gc.KeyTuple("pkt_buffer_offset", a.buf_offset),
                                    gc.KeyTuple("pkt_buffer_size", len(template))])],
                    [pbuf.make_data([gc.DataTuple("buffer", bytearray(template))])])
                wrote = True
                break
            except Exception as e:
                out["pkt_buffer_err"] = str(e)[:90]
        out["pkt_buffer"] = {"offset": a.buf_offset, "size": len(template),
                             "trial_id": a.trial_id,
                             "hex": template.hex()}
        if wrote:
            chk.ok("pkt_buffer template written",
                   "%d B at offset %d, trial_id=%d" % (len(template), a.buf_offset,
                                                       a.trial_id))
        else:
            chk.fail("pkt_buffer template written", out.get("pkt_buffer_err", "unknown"))

    # --- (3) app_cfg: one-shot timer, ONE batch of N_PACKETS ---------------
    # Counts are ZERO-BASED: batch_count_cfg=0 is one batch and
    # packets_per_batch_cfg=127 is 128 packets.
    #
    # increment_source_port MUST be False. With it true the driver caps the batch
    # at 127-68=59 tokens and would silently reject 128.
    #
    # pipe_local_source_port is REQUIRED on this silicon despite the SDE's
    # "implicit on Tofino-1" note: it sets the ingress_port the generated packets
    # carry, and without it they arrive on the wrong port, miss the parser's
    # from_pgen path and are dropped (the localising symptom is pkt_counter=N
    # with the P4's traced counter at 0 and drop_bad_port at N).
    acfg = get_table(bi, PKTGEN_APP_CFG, chk)
    if acfg is not None:
        flds = [
            gc.DataTuple("timer_nanosec", int(a.timer_ns)),
            gc.DataTuple("pkt_len", len(template)),
            gc.DataTuple("pkt_buffer_offset", a.buf_offset),
            gc.DataTuple("pipe_local_source_port", a.port_pgen),
            gc.DataTuple("increment_source_port", bool_val=False),
            gc.DataTuple("batch_count_cfg", 0),
            gc.DataTuple("packets_per_batch_cfg", N_PACKETS - 1),
            gc.DataTuple("ipg", 0),
            gc.DataTuple("ibg", 0),
            gc.DataTuple("trigger_counter", 0),
            gc.DataTuple("batch_counter", 0),
            gc.DataTuple("pkt_counter", 0),
            gc.DataTuple("app_enable", bool_val=False),
        ]
        used_tgt = None
        for tn, tgt in tgts:
            try:
                acfg.entry_mod(tgt, [acfg.make_key([gc.KeyTuple("app_id", a.app_id)])],
                               [acfg.make_data(flds, "trigger_timer_one_shot")])
                used_tgt = tn
                break
            except Exception as e:
                out["app_cfg_err"] = str(e)[:90]
        out["app_cfg"] = {"app_id": a.app_id, "trigger": "trigger_timer_one_shot",
                          "timer_nanosec": a.timer_ns, "pkt_len": len(template),
                          "batch_count_cfg": 0,
                          "packets_per_batch_cfg": N_PACKETS - 1,
                          "increment_source_port": False,
                          "pipe_local_source_port": a.port_pgen,
                          "target": used_tgt}
        if used_tgt is None:
            chk.fail("pktgen app configured", out.get("app_cfg_err", "unknown"))
        else:
            chk.ok("pktgen app %d configured (one-shot timer)" % a.app_id,
                   "1 batch x %d pkts, target=%s" % (N_PACKETS, used_tgt))
            # The pipe-0 target is preferred so ONLY pipe 0's generator fires.
            # If the SDE only accepted the device-scope target, the pipe 1/2/3
            # generators fire too; their packets carry pipe-local port 68 in
            # their own pipe (dev_port 196/324/452), miss the parser's dp68 path
            # and land on the P4's drop_bad_port counter — harmless, but it must
            # be visible rather than assumed, so the counter is part of the gate.
            #
            # TODO(silicon): whether tf1.pktgen.app_cfg accepts a pipe-scoped
            # Target on this SDE is unverified; the SDE example uses device scope
            # ("Pipe All") and the Defense 2 setup used device scope too (safe
            # there because only pipe 0 could ever see its recirc trigger).
            # RESOLVING CHECK: out["app_cfg"]["target"] records which target was
            # accepted, and the P4 counter drop_bad_port distinguishes the two
            # cases unambiguously — 0 means pipe-0 scope held, 384 (3 x 128)
            # means all four generators fired and the other three pipes' packets
            # were correctly discarded. Either way traced == 128.
            if used_tgt != "pipe0":
                chk.warn("pktgen app scoped to pipe 0",
                         "the pipe-0 target was rejected; the app is device-scoped, so "
                         "all four pipe generators fire. Expect drop_bad_port = 3 x %d "
                         "and traced = %d." % (N_PACKETS, N_PACKETS))


def read_app_counters(bi, tgts, a):
    """(trigger_counter, batch_counter, pkt_counter) or Nones."""
    acfg = get_table(bi, PKTGEN_APP_CFG)
    if acfg is None:
        return None, None, None
    for _tn, tgt in tgts:
        got, err = get_entry(acfg, tgt, [("app_id", a.app_id)])
        if not err and got is not None:
            return (got.get("trigger_counter"), got.get("batch_counter"),
                    got.get("pkt_counter"))
    return None, None, None


def read_app_enable(bi, tgts, a):
    """The generator app's app_enable flag, or None if it cannot be read.

    None is deliberately NOT treated as False anywhere: "I could not tell
    whether the generator is armed" is not the same fact as "it is disarmed",
    and the clean-state definition requires the latter.
    """
    acfg = get_table(bi, PKTGEN_APP_CFG)
    if acfg is None:
        return None
    for _tn, tg in tgts:
        got, err = get_entry(acfg, tg, [("app_id", a.app_id)])
        if not err and got is not None:
            return got.get("app_enable")
    return None


def set_app_enable(bi, tgts, a, enable, chk):
    """Flip ONLY app_enable. The app does NOT auto-disable after a one-shot
    batch, so it must be driven False before it can be re-armed True."""
    import bfrt_grpc.client as gc
    acfg = get_table(bi, PKTGEN_APP_CFG, chk)
    if acfg is None:
        return False
    for _tn, tgt in tgts:
        try:
            acfg.entry_mod(tgt, [acfg.make_key([gc.KeyTuple("app_id", a.app_id)])],
                           [acfg.make_data([gc.DataTuple("app_enable",
                                                         bool_val=enable)])])
            return True
        except Exception:
            continue
    chk.fail("pktgen app_enable=%s" % enable, "no target accepted the write")
    return False


def fire_pktgen(bi, tgts, a, out, chk):
    """Fire exactly ONE batch: disable, then enable (which starts the countdown),
    wait for pkt_counter to reach N_PACKETS, then disable again so nothing can
    re-trigger."""
    set_app_enable(bi, tgts, a, False, chk)
    t0 = time.time()
    if not set_app_enable(bi, tgts, a, True, chk):
        return
    trig = batches = pkts = None
    deadline = time.time() + a.gen_timeout
    while time.time() < deadline:
        trig, batches, pkts = read_app_counters(bi, tgts, a)
        if pkts is not None and int(pkts) >= N_PACKETS:
            break
        time.sleep(0.05)
    dt = time.time() - t0
    set_app_enable(bi, tgts, a, False, chk)
    out["pktgen_fire"] = {"trigger_counter": trig, "batch_counter": batches,
                          "pkt_counter": pkts, "seconds": round(dt, 4)}
    if pkts is None:
        chk.fail("pktgen generated %d packets" % N_PACKETS, "pkt_counter unreadable")
    else:
        chk.expect("pktgen pkt_counter", int(pkts), N_PACKETS,
                   "(%.0f ms; app disabled again)" % (dt * 1e3))


# ===========================================================================
# 5. Occupancy, P4 counters, trace
# ===========================================================================
def read_occupancy(bi, tgt0, a, out, chk, require_nonempty=False):
    """Per-queue usage_cells / watermark_cells / drop_count_packets."""
    pg_id, pg_nr = resolve_pg(bi, tgt0, a.port_l, chk, out)
    if pg_id is None:
        chk.fail("occupancy", "could not resolve dp%d pg map" % a.port_l)
        return
    ctr = get_table(bi, TM_COUNTER_QUEUE, chk)
    if ctr is None:
        return
    print("dp8 queue occupancy [%s]" % TM_COUNTER_QUEUE)
    print("  %-8s %4s %9s %12s %18s" % ("role", "qid", "usage", "watermark",
                                        "drop_count_pkts"))
    occ = {}
    for role, qid, _act in ROLES:
        pgq = pg_queue_of(pg_nr, qid)
        got, err = get_entry(ctr, tgt0, [("pg_id", pg_id), ("pg_queue", pgq)])
        if err:
            chk.fail("%s counter readback" % role, err)
            continue
        rec = {"qid": qid, "pg_queue": pgq,
               "usage_cells": got.get("usage_cells"),
               "watermark_cells": got.get("watermark_cells"),
               "drop_count_packets": got.get("drop_count_packets")}
        occ[role] = rec
        print("  %-8s %4d %9s %12s %18s" % (role, qid, rec["usage_cells"],
                                            rec["watermark_cells"],
                                            rec["drop_count_packets"]))
        drops = rec["drop_count_packets"]
        if drops is not None and int(drops) != 0:
            chk.fail("%s drop_count_packets == 0" % role,
                     "TM DROPPED %s packet(s) — the trial is VOID" % drops)
        if require_nonempty:
            use, wm = rec["usage_cells"], rec["watermark_cells"]
            if use is None or wm is None:
                chk.fail("%s demonstrably nonempty" % role, "counter readback None")
            elif int(use) > 0 and int(wm) > 0:
                chk.ok("%s demonstrably nonempty" % role,
                       "usage_cells=%s watermark_cells=%s" % (use, wm))
            else:
                # INVALID, not an ordering FAILURE. The runner records it apart.
                chk.fail("%s demonstrably nonempty" % role,
                         "usage_cells=%s watermark_cells=%s — nothing was parked on "
                         "this queue, so the trial is INVALID (not an ordering "
                         "failure)" % (use, wm))
    print("")
    out["occupancy"] = occ
    out["all_queues_nonempty"] = (
        len(occ) == 4 and all((r.get("usage_cells") or 0) > 0
                              and (r.get("watermark_cells") or 0) > 0
                              for r in occ.values()))
    out["zero_queue_drops"] = all(
        int((r or {}).get("drop_count_packets") or 0) == 0 for r in occ.values())


def queue_counters(bi, tgt0, a):
    """{role: {usage_cells, watermark_cells, drop_count_packets, ...}}, QUIET.

    No printing, no PASS/FAIL rows, no `out` mutation. read_occupancy() above is
    the loud version used at the phase boundaries; this one is called in the
    drain-poll loop and by the clean-state assertion, where a row per read would
    be noise. Returns {} if the port-group map cannot be resolved.
    """
    pg_id, pg_nr = resolve_pg_quiet(bi, tgt0, a.port_l)
    if pg_id is None:
        return {}
    ctr = get_table(bi, TM_COUNTER_QUEUE)
    if ctr is None:
        return {}
    occ = {}
    for role, qid, _act in ROLES:
        pgq = pg_queue_of(pg_nr, qid)
        got, err = get_entry(ctr, tgt0, [("pg_id", pg_id), ("pg_queue", pgq)])
        if err:
            continue
        occ[role] = {"qid": qid, "pg_queue": pgq,
                     "usage_cells": _i(got.get("usage_cells")),
                     "watermark_cells": _i(got.get("watermark_cells")),
                     "drop_count_packets": _i(got.get("drop_count_packets"))}
    return occ


def reset_queue_counters(bi, tgt0, a, out, chk):
    """Zero the three tf1.tm.counter.queue fields on the four dp8 queues.

    All three are read-write in the schema, so a write of 0 is the documented
    clear. Each field is written INDEPENDENTLY so that one rejected field cannot
    prevent the others from being cleared.

    TODO(silicon): whether this SDE accepts a write to usage_cells (a live
    occupancy gauge, unlike the latched watermark and drop counters) is
    unconfirmed off-switch. RESOLVING CHECK: any rejected field appears as a WARN
    row naming that field; if usage_cells cannot be cleared, the preload gate
    still works because it tests usage_cells > 0, not equality.
    """
    import bfrt_grpc.client as gc
    pg_id, pg_nr = resolve_pg(bi, tgt0, a.port_l, chk, out)
    if pg_id is None:
        return
    ctr = get_table(bi, TM_COUNTER_QUEUE, chk)
    if ctr is None:
        return
    for role, qid, _act in ROLES:
        pgq = pg_queue_of(pg_nr, qid)
        key = ctr.make_key([gc.KeyTuple("pg_id", pg_id), gc.KeyTuple("pg_queue", pgq)])
        for fld in CTR_FIELDS:
            try:
                ctr.entry_mod(tgt0, [key], [ctr.make_data([gc.DataTuple(fld, 0)])])
            except Exception as e:
                chk.warn("reset %s %s" % (role, fld), "TODO(silicon): %s" % str(e)[:70])
    out["queue_counters_reset"] = True


def read_p4_counters(bi, tgt, out, chk):
    """Read the P4 ctr_oracle slots."""
    vals = {}
    for idx, name in CTR_SLOTS:
        vals[name] = ctr_read(bi, tgt, "ctr_oracle", idx, chk)
    out["p4_counters"] = vals
    print("P4 ctr_oracle: " + "  ".join("%s=%s" % (k, vals[k]) for _i, k in CTR_SLOTS))
    return vals


def read_accounting(bi, tgt, chk=None):
    """The THREE on-chip accounting values, as a dict, QUIET.

    Keys are the JSON names the analyzer reads:
        total_dequeues          every packet that came back through the loopback
        trace_entries_written   those that landed in a trace slot
        trace_overflow          those the 512-entry trace could not hold
    """
    return dict((REG_JSON_KEY[n], _i(reg_read(bi, tgt, n, 0, chk)))
                for n in TRIAL_REGS)


def reset_accounting(bi, tgt, out, chk, label="trace_reset"):
    """Zero the three accounting registers and READ THEM BACK.

    The 512-entry trace ARRAYS are deliberately NOT cleared. Indices are handed
    out from 0 again once total_dequeues is zeroed, only [0, entries_written) is
    ever read, and every entry read carries the trial_id it was written with —
    so a stale entry is REJECTED by the analyzer rather than silently scored.
    Clearing 4 x 512 registers per trial would cost 2048 writes to buy nothing.
    """
    wrote = dict((n, reg_zero(bi, tgt, n, 0, chk)) for n in TRIAL_REGS)
    got = read_accounting(bi, tgt, chk)
    rec = dict(got)
    rec["wrote"] = dict((REG_JSON_KEY[n], wrote[n]) for n in TRIAL_REGS)
    out[label] = rec
    for n in TRIAL_REGS:
        chk.expect("%s zeroed" % REG_JSON_KEY[n], got[REG_JSON_KEY[n]], 0)
    return got


def read_trace_entries(bi, tgt, n, chk=None):
    """trace[0..n-1] as a list of event dicts, plus the index source."""
    if n <= 0:
        return [], "none"
    n = min(n, TRACE_LEN)
    trial, src_t = reg_read_range(bi, tgt, "trace_trial", n, chk)
    roles, _s2 = reg_read_range(bi, tgt, "trace_role", n, chk)
    pids, _s3 = reg_read_range(bi, tgt, "trace_pktid", n, chk)
    tss, _s4 = reg_read_range(bi, tgt, "trace_ts", n, chk)
    ev_list = []
    for i in range(n):
        r = _i(roles[i])
        ev_list.append({
            "pos": i,
            "trial_id": _i(trial[i]),
            "role_id": r,
            "role": ROLE_NAME.get(r),
            "pkt_id": _i(pids[i]),
            "ts_ns": _i(tss[i]),
        })
    return ev_list, src_t


def read_trace(bi, tgt, a, out, chk):
    """Read the three counters and trace[0..trace_entries_written-1].

    The number of entries read is trace_entries_written, NOT total_dequeues:
    those two differ exactly when the trace overflowed, and reading
    total_dequeues entries in that case would read slots this trial never wrote.
    Both numbers are reported so the analyzer can enforce
    total_dequeues == trace_entries_written + trace_overflow.
    """
    acct = read_accounting(bi, tgt, chk)
    out.update(acct)
    td = acct["total_dequeues"]
    tw = acct["trace_entries_written"]
    n = 0 if tw is None else min(tw, TRACE_LEN)
    if n == 0:
        out["trace"] = []
        out["index_source"] = "none"
        chk.fail("trace has events",
                 "total_dequeues=%s trace_entries_written=%s trace_overflow=%s"
                 % (td, tw, acct["trace_overflow"]))
        return
    ev_list, src_t = read_trace_entries(bi, tgt, n, chk)
    out["index_source"] = src_t
    out["trace"] = ev_list
    chk.ok("trace read", "%d event(s), index_source=%s" % (n, src_t))
    # The invariant is asserted here as well as in the analyzer, so a run that is
    # never analyzed still stops on a broken one.
    if td is not None and tw is not None and acct["trace_overflow"] is not None:
        chk.expect("total_dequeues == written + overflow", td,
                   tw + acct["trace_overflow"],
                   "(%d / %d / %d)" % (td, tw, acct["trace_overflow"]))


# ===========================================================================
# 5b. TRIAL ISOLATION — the mandatory cleanup and the clean-start assertion
#
# WHY THIS EXISTS. In the five-control pilot, control A ended INVALID with
# released=False and left 124 packets sitting in the four queues. Control B1 then
# drained A's 124 leftovers TOGETHER WITH its own 128 — a traced delta of exactly
# 252 — and every control after A began from a dirty state. Nothing in B1/B2/C/D
# is interpretable as a result. See evidence/four_queue_oracle/PILOT5_RESULT.md.
#
# The fix is not "remember to clean up". It is two mechanisms:
#   * cleanup_trial() runs on EVERY exit path, including the failure path, and
#     VERIFIES the state it leaves behind rather than assuming it;
#   * assert_clean_start() REFUSES to start a trial that is not already clean.
# Either alone would have let the pilot happen. Cleanup can fail; a trial that
# starts anyway on a dirty switch produces a plausible-looking number.
# ===========================================================================
CLEAN_FACTS = ("queues empty", "total_dequeues == 0", "trace_entries_written == 0",
               "trace_overflow == 0", "pktgen disabled")


def dp8_line_rate(bi, tgts, a, chk):
    """Put dp8 back to LINE RATE: shaping params restored, shaper DISARMED.

    Disarming (max_rate_enable=False) takes the token bucket out of the path
    entirely, so nothing downstream can depend on banked burst credit. This is
    the same single write set_port_gate(closed=False) uses to release, applied
    here as part of cleanup rather than as the measured release.
    """
    import bfrt_grpc.client as gc
    shp = get_table(bi, TM_PORT_SHAPING, chk)
    cfg = get_table(bi, TM_PORT_SCHED_CFG, chk)
    if shp is None or cfg is None:
        return False
    o = DP8_ORIGINAL
    ok = True

    def _mod(tbl, tuples):
        for _tn, tgt in tgts:
            try:
                key = tbl.make_key([gc.KeyTuple("dev_port", a.port_l)])
                tbl.entry_mod(tgt, [key], [tbl.make_data(tuples)])
                return True
            except Exception:
                continue
        return False

    ok &= _mod(cfg, [gc.DataTuple("max_rate_enable", bool_val=False)])
    ok &= _mod(shp, [gc.DataTuple("unit", str_val=o["unit"]),
                     gc.DataTuple("provisioning", str_val="UPPER"),
                     gc.DataTuple("max_rate", int(o["max_rate"])),
                     gc.DataTuple("max_burst_size", int(o["max_burst_size"]))])
    return bool(ok)


def read_clean_state(bi, tgt, tgt0, tgts, a):
    """Everything the clean-state definition depends on, as one dict.

    `clean` is True only when ALL FIVE facts hold. A fact that could not be READ
    is not clean: an unreadable queue counter is exactly the case where assuming
    cleanliness would repeat the pilot.
    """
    occ = queue_counters(bi, tgt0, a)
    acct = read_accounting(bi, tgt)
    app_en = read_app_enable(bi, tgts, a)

    usages = dict((r, (occ.get(r) or {}).get("usage_cells")) for r, _q, _x in ROLES)
    queues_empty = (len(occ) == 4 and all(u is not None and u == 0
                                          for u in usages.values()))
    st = {
        "occupancy": occ,
        "usage_cells": usages,
        "queues_empty": queues_empty,
        "app_enable": app_en,
        "pktgen_disabled": (app_en is False),
    }
    st.update(acct)
    st["clean"] = bool(
        queues_empty
        and acct["total_dequeues"] == 0
        and acct["trace_entries_written"] == 0
        and acct["trace_overflow"] == 0
        and app_en is False)
    # The facts that do NOT hold. An empty list is the definition of clean.
    st["violated_facts"] = [
        f for f, ok in (
            ("queues empty", queues_empty),
            ("total_dequeues == 0", acct["total_dequeues"] == 0),
            ("trace_entries_written == 0", acct["trace_entries_written"] == 0),
            ("trace_overflow == 0", acct["trace_overflow"] == 0),
            ("pktgen disabled", app_en is False),
        ) if not ok]
    return st


def assert_clean_start(bi, tgt, tgt0, tgts, a, out, chk):
    """REFUSE to start unless the switch is already clean. Not best-effort.

    Raises DirtyStateError, which run_trial()/run_shaper_setting() let propagate
    to their `finally`, so the cleanup path still runs and the switch is left
    better than it was found.
    """
    st = read_clean_state(bi, tgt, tgt0, tgts, a)
    out["clean_start"] = st
    if st["clean"]:
        chk.ok("CLEAN START asserted",
               "queues 0/0/0/0, all three counters 0, pktgen disabled")
        return st
    detail = ("these clean facts do NOT hold: %s | usage_cells=%s "
              "total_dequeues=%s trace_entries_written=%s trace_overflow=%s "
              "app_enable=%s"
              % (", ".join(st["violated_facts"]) or "unknown", st["usage_cells"],
                 st["total_dequeues"], st["trace_entries_written"],
                 st["trace_overflow"], st["app_enable"]))
    chk.fail("CLEAN START asserted", detail)
    raise DirtyStateError(detail)


def cleanup_trial(bi, tgt, tgt0, tgts, a, out, chk, label="cleanup"):
    """THE MANDATORY CLEANUP. Runs on every exit path, success or failure.

    Order matters and is fixed:
      1. disable pktgen               nothing new can be generated mid-cleanup
      2. dp8 back to LINE RATE        whatever is parked becomes servable
      3. drain                        give the TM time to actually dequeue it
      4. wait for usage_cells == 0    on ALL FOUR queues, polled, not assumed
      5. dequeue counter STABLE       two consecutive equal reads of
                                      total_dequeues, so a slow last packet
                                      cannot land after the reset in step 6
      6. reset registers + counters   AFTER the drain, never before: the drain
                                      itself increments total_dequeues
      7. verify the five clean facts  and record which ones failed

    Step 6 must not move ahead of step 4, and not only for the counting reason.
    reset_queue_counters() writes 0 to usage_cells, which is a LIVE occupancy
    gauge rather than a latched statistic. If that write is accepted while
    packets are still queued, step 7 would read a zeroed gauge and certify a
    switch that is still holding traffic — the exact false negative this whole
    mechanism exists to prevent. Draining FIRST and only then clearing means the
    gauge and the reality already agree before anything writes to either.
    """
    rec = {"label": label, "steps": []}

    def step(name, detail=""):
        rec["steps"].append({"step": name, "detail": str(detail)})

    # 1. disable pktgen
    ok_dis = set_app_enable(bi, tgts, a, False, chk)
    step("1 disable pktgen", "app_enable=False write_ok=%s" % ok_dis)

    # 2. dp8 back to line rate (this is what releases anything still parked)
    ok_lr = dp8_line_rate(bi, tgts, a, chk)
    step("2 dp8 to line rate", "shaper disarmed + original params, ok=%s" % ok_lr)

    # 3. drain
    time.sleep(a.cleanup_drain)
    step("3 drain", "%.2f s" % a.cleanup_drain)

    # 4. poll until every queue reads usage_cells == 0
    deadline = time.time() + a.cleanup_timeout
    usages, empty = {}, False
    while time.time() < deadline:
        occ = queue_counters(bi, tgt0, a)
        usages = dict((r, (occ.get(r) or {}).get("usage_cells")) for r, _q, _x in ROLES)
        empty = (len(occ) == 4 and all(u is not None and u == 0
                                       for u in usages.values()))
        if empty:
            break
        time.sleep(0.1)
    rec["usage_cells_after_drain"] = usages
    step("4 queues empty", "usage_cells=%s empty=%s" % (usages, empty))
    if not empty:
        chk.fail("cleanup: queues drained", "usage_cells=%s after %.1f s"
                 % (usages, a.cleanup_timeout))

    # 5. the dequeue counter must be STABLE across two consecutive reads
    stable, s1, s2 = False, None, None
    deadline = time.time() + a.cleanup_timeout
    while time.time() < deadline:
        s1 = _i(reg_read(bi, tgt, REG_TOTAL, 0))
        time.sleep(a.stable_gap)
        s2 = _i(reg_read(bi, tgt, REG_TOTAL, 0))
        if s1 is not None and s1 == s2:
            stable = True
            break
    rec["total_dequeues_stable"] = {"first": s1, "second": s2, "stable": stable}
    step("5 dequeue counter stable", "%s == %s -> %s" % (s1, s2, stable))
    if not stable:
        chk.fail("cleanup: dequeue counter stable",
                 "total_dequeues still moving (%s then %s)" % (s1, s2))

    # 6. reset the per-trial registers, the P4 counters and the TM queue counters
    for n in TRIAL_REGS:
        reg_zero(bi, tgt, n, 0, chk)
    n_ctr = sum(1 for idx, _nm in CTR_SLOTS if ctr_zero(bi, tgt, "ctr_oracle", idx))
    rec["p4_counter_slots_cleared"] = n_ctr
    if n_ctr != len(CTR_SLOTS):
        chk.warn("cleanup: P4 counters cleared",
                 "TODO(silicon): %d of %d slots accepted a write to "
                 "$COUNTER_SPEC_PKTS. The clean-start assertion does not depend "
                 "on them; the sweep reports enq_* as before/after deltas."
                 % (n_ctr, len(CTR_SLOTS)))
    reset_queue_counters(bi, tgt0, a, out, chk)
    step("6 reset registers + counters",
         "3 registers, %d/%d counter slots, TM queue counters"
         % (n_ctr, len(CTR_SLOTS)))

    # 7. verify — the same five facts a clean start requires
    st = read_clean_state(bi, tgt, tgt0, tgts, a)
    rec["verified"] = st
    rec["clean"] = st["clean"]
    step("7 verify clean", "clean=%s violated_facts=%s"
         % (st["clean"], st["violated_facts"]))
    if st["clean"]:
        chk.ok("CLEANUP verified clean", "all five facts: %s" % ", ".join(CLEAN_FACTS))
    else:
        chk.fail("CLEANUP verified clean",
                 "these clean facts do NOT hold: %s | usage_cells=%s "
                 "total_dequeues=%s trace_entries_written=%s trace_overflow=%s "
                 "app_enable=%s"
                 % (", ".join(st["violated_facts"]), st["usage_cells"],
                    st["total_dequeues"], st["trace_entries_written"],
                    st["trace_overflow"], st["app_enable"]))
    out[label] = rec
    return rec


# ===========================================================================
# 6. The whole trial
# ===========================================================================
def _trial_body(bi, tgt, tgt0, tgts, a, out, chk):
    """The measured part of a trial. Called only from run_trial(), which owns
    the clean-start assertion and the mandatory cleanup."""
    # 1. priorities for this control mode
    write_priorities(bi, tgt0, a, out, chk, write=True)

    # 2. the randomized role map
    mapping = build_role_map(a.seed)
    write_role_map(bi, tgt, a, out, chk, mapping)

    # 3. clean slate: accounting registers, queue counters, generator template
    reset_accounting(bi, tgt, out, chk)
    reset_queue_counters(bi, tgt0, a, out, chk)
    config_pktgen(bi, tgts, a, out, chk, template=build_template(a.trial_id))

    # 4. CLOSE the gate BEFORE anything is generated
    set_port_gate(bi, tgts, a, True, out, chk)

    # 5. generate the finite batch
    fire_pktgen(bi, tgts, a, out, chk)
    time.sleep(a.settle)

    # 6. THE PRELOAD GATE — all four conditions, together, BEFORE the release.
    read_occupancy(bi, tgt0, a, out, chk, require_nonempty=True)
    pre = read_accounting(bi, tgt, chk)
    out["accounting_before_release"] = pre
    out["event_ctr_before_release"] = pre["total_dequeues"]
    # Zero escapes while the gate was closed. A nonzero value means banked burst
    # credit let frames out before the release, which invalidates the boundary.
    chk.expect("zero escapes before release (total_dequeues == 0)",
               pre["total_dequeues"], 0)
    # WHICH packets escaped, not just how many: the leaked frames are already in
    # the trace, so their identity and timestamp are readable before the release.
    n_leak = pre["trace_entries_written"] or 0
    if n_leak:
        leaked, _src = read_trace_entries(bi, tgt, n_leak, chk)
        out["leaked_before_release"] = leaked
    else:
        out["leaked_before_release"] = []
    gate_rb = read_port_gate(bi, tgts, a, out, chk, label="at_preload_check")
    chk.expect("gate still closed at preload check", gate_rb.get("armed"), True)
    pre_ctr = read_p4_counters(bi, tgt, out, chk)
    out["p4_counters_before_release"] = pre_ctr

    out["preload_gate"] = {
        "all_queues_nonempty": out.get("all_queues_nonempty"),
        "zero_queue_drops": out.get("zero_queue_drops"),
        "event_ctr_before_release": out.get("event_ctr_before_release"),
        "gate_armed": gate_rb.get("armed"),
    }
    out["preload_gate_ok"] = bool(
        out.get("all_queues_nonempty") and out.get("zero_queue_drops")
        and out.get("event_ctr_before_release") == 0
        and gate_rb.get("armed") is True)

    if not out["preload_gate_ok"] and not a.release_anyway:
        chk.fail("PRELOAD GATE", "not satisfied — trial is INVALID; the release was "
                                 "NOT performed. Pass --release-anyway to override.")
        out["released"] = False
        out["verdict"] = "INVALID"
        return

    # 7. THE RELEASE — one write
    set_port_gate(bi, tgts, a, False, out, chk)
    out["released"] = True
    time.sleep(a.drain)

    # 8. read the trace and the post counters
    read_trace(bi, tgt, a, out, chk)
    out["p4_counters_after_release"] = read_p4_counters(bi, tgt, out, chk)
    read_occupancy(bi, tgt0, a, out, chk, require_nonempty=False)


def run_trial(bi, tgt, tgt0, tgts, a, out, chk):
    """ASSERT CLEAN -> reset -> map -> priorities -> close gate -> generate ->
    PRELOAD GATE -> release -> read trace -> MANDATORY CLEANUP.

    The whole trial runs in one process so the preload-check-to-release window is
    short and the release is a single local gRPC write.

    Trial isolation is structural, not procedural. The clean-start assertion is
    the FIRST thing that happens and raises rather than warning; the cleanup is in
    a `finally`, so it runs after a dirty start, after an unsatisfied preload
    gate, and after any unexpected exception. A trial that ends INVALID therefore
    leaves the switch in the same state as one that ends PASS — which is exactly
    what the five-control pilot did not do.
    """
    out["trial_id"] = a.trial_id
    out["seed"] = a.seed
    out["utc"] = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
    out.setdefault("released", False)

    try:
        assert_clean_start(bi, tgt, tgt0, tgts, a, out, chk)
        _trial_body(bi, tgt, tgt0, tgts, a, out, chk)
    except DirtyStateError as e:
        out["verdict"] = "INVALID"
        out["refused_dirty_start"] = str(e)
        chk.fail("trial REFUSED to start", str(e)[:160])
    finally:
        if a.no_cleanup:
            chk.warn("cleanup SKIPPED", "--no-cleanup was passed (debug only). "
                                        "The next trial will refuse to start.")
        else:
            cleanup_trial(bi, tgt, tgt0, tgts, a, out, chk)


# ===========================================================================
# 6b. ONE dp8 PORT-shaper setting — the screening probe used by --shaper-sweep
# ===========================================================================
def run_shaper_setting(bi, tgt, tgt0, tgts, a, out, chk):
    """Screen ONE dp8 PORT-level shaper setting for a zero-leak preload state.

    This is CHARACTERIZATION, not the scheduler experiment: all four queues get
    EQUAL max_priority, so nothing here can be read as a strict-priority result.
    The only question is whether the shaper can hold 128 packets across four
    queues with ZERO escapes until one release write.

    Screening criteria (all must hold):
        total_dequeues before release == 0     no packet escaped an armed gate
        sum(usage_cells) == 128                everything is actually parked
        every queue usage_cells > 0            all four are simultaneously backed
        queue drops == 0                       nothing was lost instead of held
        pktgen pkt_counter == 128              the batch really fired once
        after ONE release write: everything drains

    TODO(silicon): usage_cells is a CELL count, not a packet count. Control A of
    the pilot read 31/32/30/31 cells for 124 parked 64-byte frames, i.e. one cell
    per frame at this size, which is why the 128 test is written against cells.
    RESOLVING CHECK: the same run records enq_ablock+enq_ack+enq_rblock+enq_resp
    (P4 counters, packets) and pkt_counter (generator, packets). If cells and
    packets ever disagree, `occupancy_cells_total` and `enqueued_total` diverge in
    the recorded JSON and the setting is reported UNDECIDED rather than passing.
    """
    out["utc"] = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
    out["trial_id"] = a.trial_id
    out["seed"] = a.seed
    out["setting"] = {"unit": a.gate_unit, "max_rate": a.gate_rate,
                      "max_burst_size": a.gate_burst,
                      "tag": "%s:%d:%d" % (a.gate_unit, a.gate_rate, a.gate_burst)}
    out["priority_mode"] = a.priority_mode
    out.setdefault("released", False)
    screen = {}
    out["screen"] = screen

    try:
        assert_clean_start(bi, tgt, tgt0, tgts, a, out, chk)

        # EQUAL priorities. This is characterization; the ladder belongs to the
        # scheduler experiment and must not be configured here by accident.
        write_priorities(bi, tgt0, a, out, chk, write=True)
        write_role_map(bi, tgt, a, out, chk, build_role_map(a.seed))
        reset_accounting(bi, tgt, out, chk)
        reset_queue_counters(bi, tgt0, a, out, chk)
        config_pktgen(bi, tgts, a, out, chk, template=build_template(a.trial_id))

        # ARM the port shaper with this setting, then generate exactly 128.
        set_port_gate(bi, tgts, a, True, out, chk)
        fire_pktgen(bi, tgts, a, out, chk)
        time.sleep(a.settle)

        # ---- everything the screening decision needs, BEFORE the release ----
        read_occupancy(bi, tgt0, a, out, chk, require_nonempty=True)
        pre = read_accounting(bi, tgt, chk)
        out["accounting_before_release"] = pre
        out["event_ctr_before_release"] = pre["total_dequeues"]
        n_leak = pre["trace_entries_written"] or 0
        leaked, _src = read_trace_entries(bi, tgt, n_leak, chk) if n_leak else ([], "none")
        out["leaked_before_release"] = leaked
        pre_ctr = read_p4_counters(bi, tgt, out, chk)
        out["p4_counters_before_release"] = pre_ctr
        gate_rb = read_port_gate(bi, tgts, a, out, chk, label="at_preload_check")

        fire = out.get("pktgen_fire") or {}
        occ = out.get("occupancy") or {}
        usages = dict((r, (occ.get(r) or {}).get("usage_cells")) for r, _q, _x in ROLES)
        drops = dict((r, (occ.get(r) or {}).get("drop_count_packets")) for r, _q, _x in ROLES)
        enq = dict((r, pre_ctr.get("enq_%s" % r.lower())) for r, _q, _x in ROLES)
        cells_total = sum(u for u in usages.values() if u) if usages else 0
        enq_total = sum(v for v in enq.values() if v) if enq else 0

        screen.update({
            "pktgen_trigger_counter": fire.get("trigger_counter"),
            "pktgen_batch_counter": fire.get("batch_counter"),
            "pktgen_pkt_counter": _i(fire.get("pkt_counter")),
            "enqueued_per_role": enq,
            "enqueued_total": enq_total,
            "usage_cells": usages,
            "occupancy_cells_total": cells_total,
            "queue_drops": drops,
            "event_ctr_before_release": pre["total_dequeues"],
            "n_leaked": len(leaked),
            "leaked": leaked,
            "gate_armed_at_check": gate_rb.get("armed"),
        })

        screen["zero_leak"] = (pre["total_dequeues"] == 0)
        screen["all_128_parked"] = (cells_total == N_PACKETS)
        screen["every_queue_backlogged"] = (len(usages) == 4 and
                                            all(u is not None and u > 0
                                                for u in usages.values()))
        screen["zero_queue_drops"] = all((d or 0) == 0 for d in drops.values())
        screen["pktgen_generated_128"] = (screen["pktgen_pkt_counter"] == N_PACKETS)
        # Cells and packets must tell the same story, or the cell/packet
        # assumption above is wrong and this run decides nothing.
        screen["cells_agree_with_packets"] = (cells_total == enq_total)

        chk.expect("shaper screen: zero escapes", pre["total_dequeues"], 0)
        chk.expect("shaper screen: 128 parked (cells)", cells_total, N_PACKETS)
        chk.expect("shaper screen: pktgen generated", screen["pktgen_pkt_counter"],
                   N_PACKETS)

        # ---- THE RELEASE: exactly ONE write returning dp8 to line rate ----
        set_port_gate(bi, tgts, a, False, out, chk)
        out["released"] = True
        screen["release_writes"] = (out.get("gate_open") or {}).get("n_writes")
        chk.expect("release was ONE write", screen["release_writes"], 1)
        time.sleep(a.drain)

        # ---- the complete drain ----
        read_trace(bi, tgt, a, out, chk)
        out["p4_counters_after_release"] = read_p4_counters(bi, tgt, out, chk)
        read_occupancy(bi, tgt0, a, out, chk, require_nonempty=False)
        post_occ = out.get("occupancy") or {}
        post_usages = dict((r, (post_occ.get(r) or {}).get("usage_cells"))
                           for r, _q, _x in ROLES)
        screen["usage_cells_after_release"] = post_usages
        screen["total_dequeues_after_release"] = out.get("total_dequeues")
        screen["trace_entries_written_after_release"] = out.get("trace_entries_written")
        screen["trace_overflow_after_release"] = out.get("trace_overflow")
        screen["drained_completely"] = bool(
            out.get("total_dequeues") == N_PACKETS
            and out.get("trace_entries_written") == N_PACKETS
            and out.get("trace_overflow") == 0
            and all(u == 0 for u in post_usages.values() if u is not None))

        screen["pass"] = bool(
            screen["zero_leak"] and screen["all_128_parked"]
            and screen["every_queue_backlogged"] and screen["zero_queue_drops"]
            and screen["pktgen_generated_128"] and screen["drained_completely"]
            and screen["cells_agree_with_packets"])
        out["verdict"] = "PASS" if screen["pass"] else "FAIL"
    except DirtyStateError as e:
        out["verdict"] = "INVALID"
        out["refused_dirty_start"] = str(e)
        screen["pass"] = False
        chk.fail("shaper setting REFUSED to start", str(e)[:160])
    finally:
        if a.no_cleanup:
            chk.warn("cleanup SKIPPED", "--no-cleanup was passed (debug only). "
                                        "The next setting will refuse to start.")
        else:
            c = cleanup_trial(bi, tgt, tgt0, tgts, a, out, chk)
            screen["cleanup_clean"] = c.get("clean")
            if not c.get("clean"):
                screen["pass"] = False
                out["verdict"] = "INVALID"


# ===========================================================================
# CLI
# ===========================================================================
def parse_args(argv=None):
    p = argparse.ArgumentParser(
        description="control plane for the four-queue on-chip dequeue oracle")
    p.add_argument("--grpc", default="localhost:50052")
    p.add_argument("--client-id", type=int, default=0)
    p.add_argument("--prog", default=PROG_DEFAULT)

    p.add_argument("--config", action="store_true")
    p.add_argument("--verify-only", action="store_true")
    p.add_argument("--priorities", action="store_true")
    p.add_argument("--role-map", action="store_true")
    p.add_argument("--gate-close", action="store_true")
    p.add_argument("--gate-open", action="store_true")
    p.add_argument("--gate-status", action="store_true")
    p.add_argument("--occupancy", action="store_true")
    p.add_argument("--reset-trace", action="store_true")
    p.add_argument("--trace-dump", action="store_true")
    p.add_argument("--trial", action="store_true",
                   help="run the entire trial in this process")
    p.add_argument("--shaper-probe", action="store_true",
                   help="screen ONE dp8 PORT-shaper setting (equal priorities); "
                        "run/run_four_queue_oracle.sh --shaper-sweep drives this")
    p.add_argument("--assert-clean", action="store_true",
                   help="read the five clean facts and exit non-zero if dirty")
    p.add_argument("--cleanup", action="store_true",
                   help="run the mandatory cleanup path on its own")
    p.add_argument("--restore-dp8", action="store_true",
                   help="restore dp8's original scheduling configuration")
    p.add_argument("--dry-run", action="store_true")

    p.add_argument("--priority-mode", default="ladder",
                   choices=["ladder", "reversed", "equal", "tied", "custom"])
    p.add_argument("--priority", default=None,
                   help="custom mode: 'ABLOCK=7,ACK=6,RBLOCK=5,RESP=4'")
    p.add_argument("--seed", type=int, default=1,
                   help="seed for the packet_id -> role permutation")
    p.add_argument("--trial-id", type=int, default=1,
                   help="stamped into every generated frame (0..65535)")
    p.add_argument("--out", default=None, help="write the result JSON here")

    p.add_argument("--port-l", type=int, default=PORT_L)
    p.add_argument("--port-pgen", type=int, default=PORT_PGEN)
    p.add_argument("--gate-port", type=int, default=PORT_L)
    p.add_argument("--i-know-the-gate-port-is-wrong", action="store_true")
    p.add_argument("--gate-unit", default="PPS", choices=["PPS", "BPS"])
    p.add_argument("--gate-provisioning", default="UPPER",
                   choices=["UPPER", "LOWER", "MIN_ERROR"])
    p.add_argument("--gate-rate", type=int, default=1)
    p.add_argument("--gate-burst", type=int, default=0)

    p.add_argument("--app-id", type=int, default=1)
    p.add_argument("--buf-offset", type=int, default=0, help="16 B aligned")
    p.add_argument("--timer-ns", type=int, default=1000)
    p.add_argument("--gen-timeout", type=float, default=5.0)
    p.add_argument("--settle", type=float, default=0.3,
                   help="seconds between generation and the preload gate check")
    p.add_argument("--drain", type=float, default=0.5,
                   help="seconds between the release and the trace read")
    p.add_argument("--release-anyway", action="store_true",
                   help="release even if the preload gate failed (debug only)")

    # ---- inter-trial cleanup -------------------------------------------------
    p.add_argument("--cleanup-drain", type=float, default=1.0,
                   help="seconds to let the queues drain before polling them")
    p.add_argument("--cleanup-timeout", type=float, default=15.0,
                   help="seconds to wait for usage_cells == 0 and a stable "
                        "dequeue counter")
    p.add_argument("--stable-gap", type=float, default=0.25,
                   help="seconds between the two total_dequeues reads that must "
                        "be equal for the counter to count as stable")
    p.add_argument("--no-cleanup", action="store_true",
                   help="DEBUG ONLY: skip the mandatory cleanup. The next trial "
                        "will refuse to start, which is the intended behaviour.")
    return p.parse_args(argv)


def print_plan(a):
    print("")
    print("four-queue on-chip dequeue oracle — control plane")
    print("  program         : %s" % a.prog)
    print("  queues (dp%d)    : %s" % (a.port_l,
          ", ".join("%s=qid%d" % (r, q) for r, q, _x in ROLES)))
    print("  priority mode   : %s -> %s" % (a.priority_mode, priority_map(a)))
    print("  generator       : dp%d, app %d, one-shot timer %d ns, 1 batch x %d pkts"
          % (a.port_pgen, a.app_id, a.timer_ns, N_PACKETS))
    print("  role map        : %d per role, seed=%s" % (N_PER_ROLE, a.seed))
    print("  release gate    : PORT-level shaper on dp%d (%s rate=%d burst=%d);"
          % (a.gate_port, a.gate_unit, a.gate_rate, a.gate_burst))
    print("                    open = ONE write, %s max_rate_enable=False"
          % TM_PORT_SCHED_CFG)
    print("  trial isolation : assert-clean-start (REFUSES a dirty switch), "
          "cleanup in a finally")
    print("  clean facts     : %s" % ", ".join(CLEAN_FACTS))
    print("  NOT touched     : dp11, Hulk, sudo, any capture")
    print("")


def main(argv=None):
    a = parse_args(argv)
    chk = Checks()
    out = {"prog": a.prog, "authored_off_switch": True, "silicon_validated": False,
           "priority_mode": a.priority_mode, "seed": a.seed, "trial_id": a.trial_id}

    print_plan(a)
    if a.dry_run:
        out["role_map_preview"] = build_role_map(a.seed)[:16]
        print(chk.render())
        print("FQDQ " + json.dumps(out, default=str))
        if a.out:
            with open(a.out, "w") as fh:
                json.dump(out, fh, indent=2, default=str)
        return 0

    modes = [a.config, a.verify_only, a.priorities, a.role_map, a.gate_close,
             a.gate_open, a.gate_status, a.occupancy, a.reset_trace, a.trace_dump,
             a.trial, a.shaper_probe, a.assert_clean, a.cleanup, a.restore_dp8]
    if not any(modes):
        print("nothing to do: pass --trial, --shaper-probe, --assert-clean, "
              "--cleanup, --config, --verify-only, --priorities, --role-map, "
              "--gate-close, --gate-open, --gate-status, --occupancy, "
              "--reset-trace, --trace-dump, --restore-dp8 or --dry-run",
              file=sys.stderr)
        return 2

    import bfrt_grpc.client as gc
    iface = gc.ClientInterface(a.grpc, client_id=a.client_id, device_id=0,
                               notifications=None)
    iface.bind_pipeline_config(a.prog)
    bi = iface.bfrt_info_get(a.prog)
    tgt = gc.Target(device_id=0, pipe_id=0xffff)
    tgt0 = gc.Target(device_id=0, pipe_id=0)
    # dev_port-keyed fixed-function tables: pipe-0 first (so only pipe 0's
    # generator is armed), device scope as fallback. Which one this SDE accepts
    # is not decidable off-switch, so both are tried and the winner is recorded.
    tgts = [("pipe0", tgt0), ("device", tgt)]

    if a.config:
        config_ports(bi, tgt, a, out, chk)
        write_priorities(bi, tgt0, a, out, chk, write=True)
        config_pktgen(bi, tgts, a, out, chk)
        read_port_gate(bi, tgts, a, out, chk, label="at_config")
    if a.verify_only:
        write_priorities(bi, tgt0, a, out, chk, write=False)
        read_port_gate(bi, tgts, a, out, chk, label="verify")
        read_occupancy(bi, tgt0, a, out, chk)
        read_p4_counters(bi, tgt, out, chk)
    if a.priorities:
        write_priorities(bi, tgt0, a, out, chk, write=True)
    if a.role_map:
        write_role_map(bi, tgt, a, out, chk, build_role_map(a.seed))
    if a.reset_trace:
        reset_accounting(bi, tgt, out, chk)
    if a.assert_clean:
        # Read-only. It reports the five facts and fails if any is wrong; it
        # deliberately does NOT clean up, so "is it clean?" and "make it clean"
        # stay separate questions.
        st = read_clean_state(bi, tgt, tgt0, tgts, a)
        out["clean_state"] = st
        if st["clean"]:
            chk.ok("switch is CLEAN", "all five facts: %s" % ", ".join(CLEAN_FACTS))
        else:
            chk.fail("switch is CLEAN",
                     "these clean facts do NOT hold: %s | usage_cells=%s"
                     % (", ".join(st["violated_facts"]), st["usage_cells"]))
    if a.cleanup:
        cleanup_trial(bi, tgt, tgt0, tgts, a, out, chk)
    if a.gate_close:
        set_port_gate(bi, tgts, a, True, out, chk)
    if a.occupancy:
        read_occupancy(bi, tgt0, a, out, chk)
    if a.gate_status:
        read_port_gate(bi, tgts, a, out, chk, label="status")
    if a.gate_open:
        set_port_gate(bi, tgts, a, False, out, chk)
    if a.trace_dump:
        read_trace(bi, tgt, a, out, chk)
        read_p4_counters(bi, tgt, out, chk)
    if a.trial:
        run_trial(bi, tgt, tgt0, tgts, a, out, chk)
    if a.shaper_probe:
        run_shaper_setting(bi, tgt, tgt0, tgts, a, out, chk)
    if a.restore_dp8:
        restore_dp8(bi, tgts, a, out, chk)

    print(chk.render())
    out["n_fail"] = chk.n_fail
    out["checks"] = [{"result": r, "check": n, "detail": d} for r, n, d in chk.rows]
    print("FQDQ " + json.dumps(out, default=str))
    if a.out:
        with open(a.out, "w") as fh:
            json.dump(out, fh, indent=2, default=str)
        print("wrote %s" % a.out)
    return 1 if chk.n_fail else 0


if __name__ == "__main__":
    sys.exit(main())
