#!/usr/bin/env python3
"""Compose the response-only target (B' profile, M / E cache / final emitter retired):

  p0 = response-only N ingress (make_n.py, from connection/binding/generate.py's response_only profile,
       which reads integration/handshake.p4 and connection/selected.p4; native_binding.p4 is NOT an input)
       + role E egress (make_e.py, from protocol/case4_response_path.p4: padder + transport mapper,
       egress_port-dispatched parser, conn bound to egress_port)
  p1 = T (read/read_queue_timing.p4), on its two-pipe ports (read/ports.p4: 196-199)

Two pipelines only: the switch has two physical pipes (a Switch(p0,p1,p2,p3) load failed with "only 2
pipe(s) available"; BFRT $PORT shows 324-327 absent). 2cb6ecf9d's Switch(p0, p1, p2) with T in pipe 2 could
not load on it. M is retired, so T takes pipe 1.

Role prefixes n_, r_, t_ as in core/ordinary/compose.py; nothing else is changed. The response path's own
1-stage forwarding ingress is not used (N routes), so p0's ingress is N's and its egress is the response
path's. N and E are regenerated from their real inputs, which inputs.json hashes.

  python3 compose.py <out.p4>
"""
import hashlib
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
INTEG = HERE.parent.parent
sys.path.insert(0, str(INTEG / 'read'))
import compose_t_response as ct  # noqa: E402  (inline, strip_main, role, T/R sources)
import make_e  # noqa: E402
import make_n  # noqa: E402

BINDING = INTEG / 'connection' / 'binding'


def generate():
    n_text = make_n.generate()
    n_text = n_text.split('#ifndef NATIVE_BINDING_NO_MAIN')[0]
    n_text = ct.strip_main(ct.inline(n_text, BINDING))
    n_out, n_names = ct.role(n_text, 'n')
    r_out, r_names = ct.role(ct.strip_main(make_e.generate()), 'r')
    t_out, t_names = ct.role(ct.strip_main(ct.inline(ct.T_SRC.read_text(), ct.HERE)), 't')
    source = ('/* GENERATED by core/response_only/compose.py -- do not edit. Response-only target on the two-pipe\n'
              '   switch: N + B\' egress in pipe 0, T in pipe 1 (M retired). */\n#include <core.p4>\n#include <tna.p4>\n'
              + n_out + '\n' + r_out + '\n' + t_out +
              '\nPipeline(n_IgParser(), n_Ingress(), n_IgDeparser(), r_EgParser(), r_Egress(), r_EgDeparser()) p0;\n'
              'Pipeline(t_IngressParser(), t_Ingress(), t_IngressDeparser(), t_EmptyEgressParser(), t_EmptyEgress(),'
              ' t_EmptyEgressDeparser()) p1;\nSwitch(p0, p1) main;\n')
    files = [INTEG / 'handshake.p4', INTEG / 'connection' / 'selected.p4', BINDING / 'generate.py',
             BINDING / 'work_record.p4', make_e.SOURCE, ct.T_SRC, ct.HERE / 'ports.p4', ct.HERE / 'probe_shell.p4',
             HERE / 'make_n.py', HERE / 'make_e.py']
    meta = dict(inputs={p.name: hashlib.sha256(p.read_bytes()).hexdigest() for p in files},
                source_sha256=hashlib.sha256(source.encode()).hexdigest(),
                renamed=dict(n=len(n_names), r=len(r_names), t=len(t_names)),
                collisions_before_prefixing=sorted((set(n_names) & set(r_names)) | (set(n_names) & set(t_names))
                                                   | (set(r_names) & set(t_names))))
    return source, meta


if __name__ == '__main__':
    out = Path(sys.argv[1])
    src, meta = generate()
    out.write_text(src)
    out.with_suffix('.inputs.json').write_text(json.dumps(meta, indent=2) + '\n')
    print('wrote', out, meta['renamed'], 'collisions before prefixing:', meta['collisions_before_prefixing'])
