"""Emit the exact Option B (uniform 58-byte) filler objects used by the pad58 gate.

Unlike case4_padding's decoy and case4_qualifier_rewrite's rewritten header,
case4_pad58 transforms RESPONSES only and never touches the request; its
filler is a pure append whose bytes do not depend on the native object it
follows. That means (unlike the other two emit_vectors*.py scripts) this
script never needs to synthesize a native frame -- it calls
`case4_pad58._analog_object` directly for the two point sets the active
codec uses (one READ filler point, three SELECT/OPERATE filler points) and
emits the exact bytes `case4_pad58.pad_read_response`/`pad_control_response`
would append to a real frame. The C++ test appends this same hex to a REAL
production outstation's live response rather than reconstructing a frame in
Python, since the native frame only exists at C++ runtime.
"""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import case4_pad58 as pad58

read_points = (pad58.AnalogPoint(301, 1234, 0x02),)
control_points = (pad58.AnalogPoint(301, 10, 0), pad58.AnalogPoint(302, 20, 0), pad58.AnalogPoint(303, 30, 0))
assert len(read_points) == pad58.READ_FILLER_POINTS
assert len(control_points) == pad58.CONTROL_FILLER_POINTS
read_filler = pad58._analog_object(read_points)
control_filler = pad58._analog_object(control_points)
assert (len(read_filler), len(control_filler)) == (9, 19)
print('// Generated by emit_vectors_pad58.py from the strict Option B (case4_pad58) codec.')
print('const std::string readFillerObject = "' + read_filler.hex(' ').upper() + '";')
print('const std::string controlFillerObject = "' + control_filler.hex(' ').upper() + '";')
print('const std::string readHeader23 = "' + pad58.HEADER_READ23.hex(' ').upper() + '";')
print('const std::string controlHeader28 = "' + pad58.HEADER_CROB28.hex(' ').upper() + '";')
