"""Emit the exact qualifier-rewrite bytes used by the qualifier-rewrite gate.

Uses the same real master-generated `native` vector as emit_vectors.py (that
vector is verified there to equal the actual production master's wire output
for SelectAndOperate(CROB, index=1)), so transformedSelect is directly
comparable to the separate-header gate's padded vectors.
"""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import case4_padding as p
import case4_qualifier_rewrite as qr
native = bytes.fromhex('c0c0030c0128010001000101640000006400000000')
f = p.build_frame(bytes.fromhex('056400c40a000100'), native)
x, delta = qr.rewrite_qualifier(f, p.Decoy(201, bytes.fromhex('0101640000006400000000')))
_, user = p.decode_frame(x)
assert (len(f), len(x), delta, len(user) - 1) == (35, 45, 10, 30)
print('// Generated by emit_vectors_qualifier.py from the strict qualifier-rewrite transformer.')
print('const std::string nativeSelect = "' + native[1:].hex(' ').upper() + '";')
print('const std::string transformedSelect = "' + user[1:].hex(' ').upper() + '";')
print('const std::string transformedFrame = "' + x.hex(' ').upper() + '";')
