"""Emit the exact Option B' (whitelisted-qualifier) filler objects used by the pad58b gate.

Unlike case4_padding's decoy and case4_qualifier_rewrite's rewritten header,
case4_pad58b transforms RESPONSES only and never touches the request; both of
its fillers are pure appends whose bytes do not depend on the native object
they follow. That means (unlike case4_padding/case4_qualifier_rewrite's own
emit_vectors*.py scripts) this script never needs to synthesize a native
frame -- it calls `case4_pad58b.READ_FILLER` directly (the READ filler is a
fixed constant, no point data at all) and `case4_pad58b._analog_float_object`
for the two-point CONTROL filler, emitting the exact bytes
`case4_pad58b.pad_read_response`/`pad_control_response` would append to a
real frame. The C++ test appends this same hex to a REAL production
outstation's live response rather than reconstructing a frame in Python,
since the native frame only exists at C++ runtime.
"""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import case4_pad58b as pad58b

control_points = (pad58b.AnalogFloatPoint(301, 10.0, 0), pad58b.AnalogFloatPoint(302, 20.0, 0))
assert len(control_points) == pad58b.CONTROL_FILLER_POINTS
read_filler = pad58b.READ_FILLER
control_filler = pad58b._analog_float_object(control_points)
assert (len(read_filler), len(control_filler)) == (9, 19)
print("// Generated by emit_vectors_pad58b.py from the strict Option B' (case4_pad58b) codec.")
print('const std::string readFillerObject = "' + read_filler.hex(' ').upper() + '";')
print('const std::string controlFillerObject = "' + control_filler.hex(' ').upper() + '";')
print('const std::string readHeader23 = "' + pad58b.HEADER_READ23.hex(' ').upper() + '";')
print('const std::string controlHeader28 = "' + pad58b.HEADER_CROB28.hex(' ').upper() + '";')
