"""Emit the exact separate-header bytes used by the production-context gate."""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import case4_padding as p
native = bytes.fromhex('c0c0030c0128010001000101640000006400000000')
f = p.build_frame(bytes.fromhex('056400c40a000100'), native)
x, delta = p.expand_control(f, p.Decoy(201, bytes.fromhex('0101640000006400000000')))
_, user = p.decode_frame(x)
assert (len(f), len(x), delta, len(user) - 1) == (35, 55, 20, 38)
print('// Generated by emit_vectors.py from the strict wire transformer.')
print('const std::string paddingObjects = "' + user[21:].hex(' ').upper() + '";')
print('const std::string nativeSelect = "' + native[1:].hex(' ').upper() + '";')
print('const std::string transformedSelect = "' + user[1:].hex(' ').upper() + '";')
print('const std::string transformedFrame = "' + x.hex(' ').upper() + '";')
