// Generated by emit_vectors.py from the strict wire transformer.
const std::string paddingObjects = "0C 01 28 01 00 C9 00 01 01 64 00 00 00 64 00 00 00 00";
const std::string nativeSelect = "C0 03 0C 01 28 01 00 01 00 01 01 64 00 00 00 64 00 00 00 00";
const std::string transformedSelect = "C0 03 0C 01 28 01 00 01 00 01 01 64 00 00 00 64 00 00 00 00 0C 01 28 01 00 C9 00 01 01 64 00 00 00 64 00 00 00 00";
const std::string transformedFrame = "05 64 2C C4 0A 00 01 00 10 FE C0 C0 03 0C 01 28 01 00 01 00 01 01 64 00 00 00 58 5B 64 00 00 00 00 0C 01 28 01 00 C9 00 01 01 64 00 6D C8 00 00 64 00 00 00 00 00 5B";
