// Generated by emit_vectors_pad58b.py from the strict Option B' (case4_pad58b) codec.
const std::string readFillerObject = "29 01 06 29 02 06 29 03 06";
const std::string controlFillerObject = "29 03 28 02 00 2D 01 00 00 20 41 00 2E 01 00 00 A0 41 00";
const std::string readHeader23 = "0A 02 00 00 16";
const std::string controlHeader28 = "0C 01 28 01 00";
