#!/usr/bin/env python3
"""p13_inject.py — two-sided DNP3 replay injector for the Part 13 silicon gates.

TWO MODES, ONE FILE, ON PURPOSE.

  --build-plan   runs LOCALLY on the dev box, offline, unprivileged. Reads the Gate 13.1 replay
                 spec, calls build_replay_frames.build() to produce the wire frames, adds the
                 blocker tokens from p13_tokens, and writes ONE plan JSON holding every frame
                 with the side that must send it and its send offset in milliseconds.

  --side X       runs ON VISION or ON HULK as root. Reads that same plan, keeps only its own
                 side's events, waits for a shared absolute start time, and plays them from a
                 local monotonic clock.

The two modes live in one module so the schedule that gets reviewed is byte-for-byte the
schedule that gets injected. A separate planner would be free to drift from the player.

WHY TWO SIDES AT ALL. Parts 9-12 injected every role from Hulk, because a synthetic role byte
carried its own identity. Real DNP3 has no such byte: `ibspg_dnp3.p4` derives direction from the
INGRESS PORT in its parser. So a READ has to physically arrive on dp9 and an outstation frame on
dp11:

    READ (master -> outstation, dir 0)          VISION -> dp9
    pure ACK and RESPONSE (dir 1)               HULK   -> dp11
    blocker tokens (ethertype 0x88C1)           HULK   -> dp11 (forced ROLE_BLOCK in the parser)

SYNCHRONISATION, AND WHAT IT ACTUALLY HAS TO ACHIEVE. Every interval this gate measures — the
ACK -> RESPONSE CLRT — is generated by ONE process on ONE host (Hulk sends both), so it carries
no cross-host clock error at all. The only cross-host requirement is an ORDERING one: the READ
must arrive before the tokens and before the ACK. That is enforced with a lead time, not with
tight synchronisation:

  * both injectors are handed the same absolute --start-epoch and sleep until it;
  * Vision sends its READ at offset 0, Hulk sends tokens at --tok-lead-ms and the ACK at
    --ack-lead-ms after that same epoch;
  * so the ordering survives any clock skew smaller than the lead (default 20 ms to the tokens).

And the ordering is not merely hoped for — it is WITNESSED ON CHIP. If an ACK beat its READ, the
slot would not be armed, `meta.active_now` would be 0, and the ACK would land in
`ctr_ack_bypass` instead of `ctr_ack_arm`. If a token beat its READ, `reg_gen` would still hold
the previous generation and the token would self-terminate into `ctr_block_term_stale`. Both
counters are read every trial, so skew that actually mattered is visible as a number rather than
as a silent wrong result.

SUDO. A raw AF_PACKET socket without root raises PermissionError. A swallowed one injects
nothing and looks exactly like a dead link, so this script exits 2 and says so.

Python 3.8+, stdlib only.

Examples:
  # local, offline
  python3 p13_inject.py --build-plan --mode hold_resp --k 64 --ntxn 30 --out plan.json
  python3 p13_inject.py --build-plan --selftest --mode hold_resp --k 64
  # on a host, as root
  sudo python3 p13_inject.py --side vision --plan plan.json --iface enp59s0f0np0 \\
       --start-epoch 1785000000.0
"""
import argparse
import json
import os
import socket
import struct
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
REPLAY_DIR = os.path.dirname(HERE)

# build_replay_frames and p13_tokens are imported LAZILY, inside the planning path only.
# Consequence, and the reason it is done this way: injecting needs nothing but this one file
# and a plan JSON, so staging to Vision and Hulk is two files instead of four and cannot break
# on a directory layout that differs from the dev box.
brf = None
p13_tokens = None


def _load_planning_modules():
    global brf, p13_tokens
    if brf is not None:
        return
    if REPLAY_DIR not in sys.path:
        sys.path.insert(0, REPLAY_DIR)
    if HERE not in sys.path:
        sys.path.insert(0, HERE)
    import build_replay_frames as _brf          # frame building is REUSED, never reimplemented
    import p13_tokens as _tok
    brf = _brf
    p13_tokens = _tok


SIDES = ("vision", "hulk")
MODES = ("bypass", "hold_ack", "hold_resp")

# Roles as they appear in the plan. READ/PURE_ACK/RESPONSE come straight out of
# build_replay_frames; BLOCK is this harness's addition.
ROLE_READ = "READ"
ROLE_ACK = "PURE_ACK"
ROLE_RESP = "RESPONSE"
ROLE_BLOCK = "BLOCK"

# Which host must originate each role, from the ingress-port direction contract above.
ROLE_SIDE = {ROLE_READ: "vision", ROLE_ACK: "hulk", ROLE_RESP: "hulk", ROLE_BLOCK: "hulk"}

ETYPE_TOKEN = 0x88C1        # kept local so selftest_plan() needs no import

# Spin for the last stretch before a send instead of sleeping: time.sleep() on Linux overshoots
# by up to ~1 ms, which is the same order as the intervals being scheduled.
SPIN_WINDOW_S = 0.0015


# ------------------------------------------------------------------ planning ----
def _mode_uses_tokens(mode):
    """bypass is the no-hold baseline: no reservoir, so the response is never held.

    hold_ack and hold_resp both need the reservoir. See the note on hold_ack in build_plan().
    """
    return mode != "bypass"


def build_plan(spec_path, mode, k, budget, ntxn, txn_period_ms, tok_lead_ms, ack_lead_ms,
               resp_delay_ms, token_gap_ms, runid, frames_path=None):
    """Assemble the full two-sided schedule. Pure computation; touches no network."""
    if mode not in MODES:
        raise ValueError("mode must be one of %s" % (MODES,))
    _load_planning_modules()
    spec = p13_tokens.load_spec(spec_path)
    if ntxn:
        spec = dict(spec, transactions=spec["transactions"][:ntxn])
    txns = spec["transactions"]
    if not txns:
        raise ValueError("no transactions in %s" % spec_path)

    # Frames come from the committed builder, never from a local reimplementation.
    frames = brf.build(spec)

    by_txn = {}
    for f in frames:
        by_txn.setdefault(f["txn"], []).append(f)

    use_tokens = _mode_uses_tokens(mode)
    events = []
    index = []

    for t in txns:
        txn = t["txn"]
        base = float(txn) * float(txn_period_ms)
        group = by_txn[txn]
        read = next(f for f in group if f["role"] == ROLE_READ)
        ack = next(f for f in group if f["role"] == ROLE_ACK)
        resps = [f for f in group if f["role"] == ROLE_RESP]

        pr = brf.parse_back(read["frame"])
        pa = brf.parse_back(ack["frame"])
        read_payload = pr["payload"]
        gen = p13_tokens.gen_from_read_payload(read_payload)

        # 1) the READ, from Vision, at the transaction origin
        events.append({"side": "vision", "role": ROLE_READ, "txn": txn,
                       "offset_ms": base, "repeat": 1, "gap_ms": 0.0,
                       "hex": read["frame"].hex()})

        # 2) the blocker reservoir, from Hulk, once the READ has armed the generation
        token_hex = None
        if use_tokens and k > 0:
            token = p13_tokens.build_token(gen, budget)
            token_hex = token.hex()
            events.append({"side": "hulk", "role": ROLE_BLOCK, "txn": txn,
                           "offset_ms": base + tok_lead_ms, "repeat": int(k),
                           "gap_ms": float(token_gap_ms), "hex": token_hex})

        # 3) the pure ACK, from Hulk — forwarded immediately, arms deadline = t_ack + G
        events.append({"side": "hulk", "role": ROLE_ACK, "txn": txn,
                       "offset_ms": base + ack_lead_ms, "repeat": 1, "gap_ms": 0.0,
                       "hex": ack["frame"].hex()})

        # 4) the RESPONSE(s), from Hulk, a controllable delay after the ACK
        resp_entries = []
        for i, r in enumerate(resps):
            off = base + ack_lead_ms + resp_delay_ms + i * float(resp_delay_ms)
            events.append({"side": "hulk", "role": ROLE_RESP, "txn": txn,
                           "offset_ms": off, "repeat": 1, "gap_ms": 0.0,
                           "hex": r["frame"].hex()})
            p = brf.parse_back(r["frame"])
            resp_entries.append({"seq": p["seq"], "payload_len": p["payload_len"],
                                 "payload_hex": p["payload"].hex(),
                                 "frame_hex": r["frame"].hex(), "offset_ms": off})

        index.append({
            "txn": txn,
            "gen": gen,
            "gen_hex": "0x%02x" % gen,
            "app_seq": t["req"].get("app_seq"),
            "read": {"seq": pr["seq"], "payload_len": pr["payload_len"],
                     "payload_hex": read_payload.hex(), "frame_hex": read["frame"].hex(),
                     "offset_ms": base},
            "ack": {"ack_no": pa["ack"], "seq": pa["seq"], "frame_hex": ack["frame"].hex(),
                    "offset_ms": base + ack_lead_ms},
            "resp": resp_entries,
            "token_hex": token_hex,
            "observed_ms": t.get("observed_ms"),
        })

    events.sort(key=lambda e: (e["offset_ms"], 0 if e["side"] == "vision" else 1))
    for n, e in enumerate(events):
        e["n"] = n

    duration_ms = max(e["offset_ms"] for e in events) if events else 0.0
    plan = {
        "runid": runid,
        "mode": mode,
        "source_spec": os.path.basename(spec_path),
        "ntxn": len(txns),
        "k": (int(k) if use_tokens else 0),
        "budget": budget,
        "uses_tokens": use_tokens,
        "schedule": {
            "txn_period_ms": txn_period_ms,
            "tok_lead_ms": tok_lead_ms,
            "ack_lead_ms": ack_lead_ms,
            "resp_delay_ms": resp_delay_ms,
            "token_gap_ms": token_gap_ms,
            "duration_ms": duration_ms,
        },
        "addressing": {"master": brf.IP_MASTER, "outstation": brf.IP_OUTSTATION,
                       "dnp3_port": brf.PORT_DNP3, "master_port": brf.PORT_MASTER,
                       "src_mac": brf.MAC_NEUTRAL, "dst_mac": brf.MAC_VISION},
        "sides": {"vision": "dp9 / dir 0 — READ only",
                  "hulk": "dp11 / dir 1 — pure ACK, RESPONSE, blocker tokens"},
        "generation_contract": "token gen = DNP3 application control byte of the guarded READ",
        "event_count": len(events),
        "txns": index,
        "events": events,
    }
    if frames_path and os.path.exists(frames_path):
        plan["frames_crosscheck"] = _crosscheck_frames(frames, frames_path)
    return plan


def _crosscheck_frames(frames, frames_path):
    """Confirm the frames built here are byte-identical to the committed replay_frames JSON.

    Cheap insurance that nothing in this harness silently re-derives what the audited builder
    already produced.
    """
    with open(frames_path) as fh:
        ref = json.load(fh)
    ref_by = {}
    for f in ref["frames"]:
        ref_by.setdefault((f["txn"], f["role"]), []).append(f["hex"])
    seen = {}
    match = mismatch = absent = 0
    for f in frames:
        key = (f["txn"], f["role"])
        i = seen.get(key, 0)
        seen[key] = i + 1
        cand = ref_by.get(key)
        if cand is None or i >= len(cand):
            absent += 1
        elif cand[i] == f["frame"].hex():
            match += 1
        else:
            mismatch += 1
    return {"file": os.path.basename(frames_path), "match": match,
            "mismatch": mismatch, "absent_from_reference": absent}


def selftest_plan(plan, frames_path=None):
    """Validate the schedule offline. Returns (ok_count, [failures])."""
    ok = 0
    fails = []

    def chk(name, good):
        nonlocal ok
        if good:
            ok += 1
        else:
            fails.append(name)

    events = plan["events"]
    txns = plan["txns"]

    chk("plan has events", bool(events))
    chk("event count matches", plan["event_count"] == len(events))
    chk("offsets are non-decreasing", all(events[i]["offset_ms"] <= events[i + 1]["offset_ms"]
                                          for i in range(len(events) - 1)))

    for e in events:
        chk("role %s on side %s" % (e["role"], e["side"]), ROLE_SIDE[e["role"]] == e["side"])
        chk("event %d has a frame" % e["n"], bool(e["hex"]) and len(e["hex"]) % 2 == 0)
        chk("event %d repeat >= 1" % e["n"], e["repeat"] >= 1)

    # side split: exactly the direction contract
    v = [e for e in events if e["side"] == "vision"]
    h = [e for e in events if e["side"] == "hulk"]
    chk("vision sends only READs", all(e["role"] == ROLE_READ for e in v))
    chk("hulk sends no READs", all(e["role"] != ROLE_READ for e in h))
    chk("one READ per transaction", len(v) == len(txns))

    if plan["mode"] == "bypass":
        chk("bypass mode injects no tokens",
            not any(e["role"] == ROLE_BLOCK for e in events))
    elif plan["k"] > 0:
        chk("one token event per transaction",
            len([e for e in events if e["role"] == ROLE_BLOCK]) == len(txns))
        chk("token repeat == K",
            all(e["repeat"] == plan["k"] for e in events if e["role"] == ROLE_BLOCK))

    # per-transaction ordering and the generation contract
    ack_keys = set()
    resp_keys = set()
    for t in txns:
        txn = t["txn"]
        ev = [e for e in events if e["txn"] == txn]
        o_read = min(e["offset_ms"] for e in ev if e["role"] == ROLE_READ)
        o_ack = min(e["offset_ms"] for e in ev if e["role"] == ROLE_ACK)
        o_resp = min(e["offset_ms"] for e in ev if e["role"] == ROLE_RESP)
        chk("txn %s READ before ACK" % txn, o_read < o_ack)
        chk("txn %s ACK before RESPONSE" % txn, o_ack < o_resp)
        toks = [e for e in ev if e["role"] == ROLE_BLOCK]
        if toks:
            o_tok = min(e["offset_ms"] for e in toks)
            chk("txn %s READ before tokens" % txn, o_read < o_tok)
            chk("txn %s tokens before ACK" % txn, o_tok < o_ack)
            tf = bytes.fromhex(toks[0]["hex"])
            chk("txn %s token gen == READ app control" % txn, tf[16] == t["gen"])
            chk("txn %s token ethertype 0x88C1" % txn,
                struct.unpack("!H", tf[12:14])[0] == ETYPE_TOKEN)

        payload = bytes.fromhex(t["read"]["payload_hex"])
        chk("txn %s gen == payload[11]" % txn, t["gen"] == payload[11])
        chk("txn %s READ func code is 0x01" % txn, payload[12] == 0x01)
        chk("txn %s expected_ack == read.seq + payload_len" % txn,
            t["ack"]["ack_no"] == ((t["read"]["seq"] + t["read"]["payload_len"]) & 0xFFFFFFFF))
        # the verifier joins pcap frames to transactions on these two numbers, so they must
        # be unique across the whole campaign or the join is ambiguous
        chk("txn %s ack_no unique" % txn, t["ack"]["ack_no"] not in ack_keys)
        ack_keys.add(t["ack"]["ack_no"])
        for r in t["resp"]:
            chk("txn %s resp seq unique" % txn, r["seq"] not in resp_keys)
            resp_keys.add(r["seq"])
            chk("txn %s resp func code is 0x81" % txn, bytes.fromhex(r["payload_hex"])[12] == 0x81)

    # transactions must not overlap: the last event of txn i precedes the first of txn i+1
    for i in range(len(txns) - 1):
        a_last = max(e["offset_ms"] for e in events if e["txn"] == txns[i]["txn"])
        b_first = min(e["offset_ms"] for e in events if e["txn"] == txns[i + 1]["txn"])
        chk("txn %s finishes before txn %s starts" % (txns[i]["txn"], txns[i + 1]["txn"]),
            a_last < b_first)

    cc = plan.get("frames_crosscheck")
    if cc:
        chk("every frame matches replay_frames_sel751.json",
            cc["mismatch"] == 0 and cc["absent_from_reference"] == 0 and cc["match"] > 0)
    elif frames_path:
        fails.append("frames cross-check file missing: %s" % frames_path)

    return ok, fails


# ------------------------------------------------------------------ injecting ----
def open_raw(iface):
    """Raw AF_PACKET socket bound to iface. Fails loudly, never silently."""
    try:
        s = socket.socket(socket.AF_PACKET, socket.SOCK_RAW)
    except AttributeError:
        sys.stderr.write("FATAL: AF_PACKET is Linux-only; run this on Vision or Hulk.\n")
        sys.exit(2)
    except PermissionError as e:
        sys.stderr.write(
            "FATAL: raw AF_PACKET socket denied (%s). This script MUST run as root (sudo). "
            "Without it nothing is injected and the trial reads all-zero counters, which looks "
            "exactly like a dead link.\n" % e)
        sys.exit(2)
    except OSError as e:
        sys.stderr.write("FATAL: could not create raw socket: %s\n" % e)
        sys.exit(2)
    try:
        s.bind((iface, 0))
    except OSError as e:
        sys.stderr.write("FATAL: could not bind raw socket to iface %r: %s\n" % (iface, e))
        sys.exit(2)
    return s


def _wait_until_mono(target):
    """Sleep then spin. sleep() alone overshoots by ~1 ms, which is the scheduling granularity."""
    while True:
        d = target - time.monotonic()
        if d <= 0:
            return
        if d > SPIN_WINDOW_S:
            time.sleep(d - SPIN_WINDOW_S)


def play(events, sock, start_epoch, dry_run=False):
    """Align to the shared absolute epoch, then run the schedule off the monotonic clock."""
    now = time.time()
    align_wait = start_epoch - now
    if align_wait > 0:
        time.sleep(align_wait)
    elif align_wait < -0.050:
        sys.stderr.write("WARN: start epoch was already %.3f s in the past; the schedule will "
                         "run late and cross-host ordering may not hold.\n" % (-align_wait,))

    base_mono = time.monotonic()
    base_epoch = time.time()
    sent = 0
    lateness_ms = []
    log = []
    for e in events:
        target = base_mono + e["offset_ms"] / 1000.0
        _wait_until_mono(target)
        actual = time.monotonic()
        frame = bytes.fromhex(e["hex"])
        gap = e.get("gap_ms", 0.0) / 1000.0
        rep = int(e.get("repeat", 1))
        if not dry_run:
            for i in range(rep):
                sock.send(frame)
                if gap > 0 and i + 1 < rep:
                    time.sleep(gap)
        sent += rep
        late = (actual - target) * 1000.0
        lateness_ms.append(late)
        log.append({"n": e["n"], "role": e["role"], "txn": e["txn"],
                    "planned_ms": e["offset_ms"], "actual_ms": round((actual - base_mono) * 1000.0, 3),
                    "late_ms": round(late, 3), "repeat": rep, "bytes": len(frame)})
    return {"sent": sent, "lateness_ms": lateness_ms, "log": log,
            "base_epoch": base_epoch, "align_wait_s": round(align_wait, 6)}


def main():
    ap = argparse.ArgumentParser(description="two-sided DNP3 replay injector")
    ap.add_argument("--build-plan", action="store_true", help="build the plan locally and exit")
    ap.add_argument("--side", choices=list(SIDES), help="inject this side's events")
    ap.add_argument("--plan", default=None, help="plan JSON (input when injecting, output when building)")
    ap.add_argument("--out", default=None, help="where --build-plan writes the plan")
    ap.add_argument("--iface", default="enp59s0f0np0")
    ap.add_argument("--start-epoch", type=float, default=None,
                    help="absolute CLOCK_REALTIME seconds at which offset 0 fires on BOTH hosts")
    ap.add_argument("--dry-run", action="store_true",
                    help="walk the schedule without opening a socket or sending (timing check)")

    ap.add_argument("--spec", default=os.path.join(REPLAY_DIR, "replay_spec_sel751.json"))
    ap.add_argument("--frames", default=os.path.join(REPLAY_DIR, "replay_frames_sel751.json"),
                    help="committed frame list, used only to cross-check the rebuild")
    ap.add_argument("--mode", default="hold_resp", choices=list(MODES))
    ap.add_argument("--k", type=int, default=64, help="blocker reservoir depth")
    ap.add_argument("--budget", type=int, default=2000000, help="blocker pass budget")
    ap.add_argument("--ntxn", type=int, default=0, help="first N transactions (0 = all 30)")
    ap.add_argument("--txn-period-ms", type=float, default=250.0)
    ap.add_argument("--tok-lead-ms", type=float, default=20.0,
                    help="READ -> tokens lead; must exceed the Vision/Hulk clock offset")
    ap.add_argument("--ack-lead-ms", type=float, default=70.0, help="READ -> ACK lead")
    ap.add_argument("--resp-delay-ms", type=float, default=2.0,
                    help="ACK -> RESPONSE spacing; keep well under G")
    ap.add_argument("--token-gap-ms", type=float, default=0.0)
    ap.add_argument("--runid", default="p13")
    ap.add_argument("--selftest", action="store_true", help="validate the plan offline")
    a = ap.parse_args()

    if a.build_plan:
        if a.tok_lead_ms >= a.ack_lead_ms:
            sys.stderr.write("FATAL: --tok-lead-ms must be < --ack-lead-ms (the reservoir has to "
                             "be looping before the ACK arms the deadline).\n")
            return 2
        if a.tok_lead_ms <= 0:
            sys.stderr.write("FATAL: --tok-lead-ms must be > 0 (the READ arms the generation the "
                             "tokens are stamped with; a token that beats its READ is stale).\n")
            return 2
        plan = build_plan(a.spec, a.mode, a.k, a.budget, a.ntxn, a.txn_period_ms,
                          a.tok_lead_ms, a.ack_lead_ms, a.resp_delay_ms, a.token_gap_ms,
                          a.runid, frames_path=a.frames)
        rc = 0
        if a.selftest:
            ok, fails = selftest_plan(plan, frames_path=a.frames)
            for f in fails:
                sys.stderr.write("  FAIL %s\n" % f)
            print("selftest: %d checks passed, %d failed, over %d transactions / %d events"
                  % (ok, len(fails), plan["ntxn"], plan["event_count"]))
            rc = 1 if fails else 0
        dest = a.out or a.plan
        if dest:
            with open(dest, "w") as fh:
                json.dump(plan, fh, indent=1)
            print("wrote %s (%d events, %d txns, mode=%s, k=%d, %.0f ms long)"
                  % (dest, plan["event_count"], plan["ntxn"], plan["mode"], plan["k"],
                     plan["schedule"]["duration_ms"]))
        return rc

    if not a.side:
        sys.stderr.write("FATAL: give either --build-plan or --side vision|hulk.\n")
        return 2
    if not a.plan:
        sys.stderr.write("FATAL: --plan is required when injecting.\n")
        return 2
    with open(a.plan) as fh:
        plan = json.load(fh)

    mine = [e for e in plan["events"] if e["side"] == a.side]
    mine.sort(key=lambda e: e["offset_ms"])

    start_epoch = a.start_epoch if a.start_epoch is not None else time.time() + 1.0
    sock = None
    if not a.dry_run and mine:
        sock = open_raw(a.iface)
    t_open = time.time()

    res = play(mine, sock, start_epoch, dry_run=a.dry_run)
    if sock is not None:
        sock.close()

    roles = {}
    for e in mine:
        roles[e["role"]] = roles.get(e["role"], 0) + int(e.get("repeat", 1))
    lm = res["lateness_ms"]
    out = {
        "side": a.side,
        "iface": a.iface,
        "runid": plan.get("runid"),
        "mode": plan.get("mode"),
        "dry_run": bool(a.dry_run),
        "events": len(mine),
        "frames_sent": res["sent"],
        "roles": roles,
        "start_epoch": start_epoch,
        "socket_open_epoch": round(t_open, 6),
        "first_send_epoch": round(res["base_epoch"], 6),
        "align_wait_s": res["align_wait_s"],
        "max_late_ms": (round(max(lm), 3) if lm else None),
        "mean_late_ms": (round(sum(lm) / len(lm), 3) if lm else None),
        "schedule": plan.get("schedule"),
        "log": res["log"],
    }
    print("P13INJ " + json.dumps(out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
