#!/usr/bin/env bash
# =============================================================================
#  run_defense3.sh — the TRANSACTIONAL driver for DEFENSE 3, §13 GATE 2.
#
#  ONE synthetic transaction, then STOP. There is deliberately no flag that
#  continues past one: Gates 3 and 4 are separate, human-gated steps and this
#  script does not contain them.
#
#  ---------------------------------------------------------------------------
#  RESTORATION IS NOT REIMPLEMENTED HERE.
#
#  The EXIT / INT / TERM / HUP trap calls
#
#      research/case_a_read_anchored_dual_release/run/run_four_queue_oracle.sh \
#          --restore-only --no-tmux
#
#  which is the PROVEN restore path: converge-to-known-good (it does NOT cycle a
#  healthy switch), then verify five facts — p4_name, strict_priority_verified,
#  app_enable, exactly one bf_switchd, dp8 shaping restored. That path has worked
#  repeatedly including from a real failure. Nothing about it is copied, edited
#  or re-derived here, and the frozen tree is NOT modified.
#
#  Two mechanical details make the delegation work, and both have bitten before:
#    * the child gets its OWN lockfile. This script holds the shared hardware
#      lock for the whole run; if the child tried to take the same one its
#      `flock -n` would fail and RESTORATION WOULD SILENTLY NOT HAPPEN.
#    * the child is invoked with --no-tmux so it runs inline in this process
#      tree and its output is captured, rather than detaching into a session.
#
#  ►► WHAT THE RESTORE RESTORES, STATED PLAINLY: it returns the switch to
#     DEFENSE 2 (`dnp3_timing_normalizer_pktgen`). That is the project's
#     known-good state and it is what "transactional" means here. It also means
#     a SECOND --gate2 run needs the Defense 3 synthetic build re-loaded first,
#     which is a separate, explicitly authorized step that this script will not
#     take. If you are mid-campaign and want the switch left on Defense 3, run
#     with D3_SKIP_RESTORE=1 — and then you own restoring it.
#
#  ---------------------------------------------------------------------------
#  MODES
#    --gate2         ONE synthetic transaction, then STOP. Requires the
#                    SYNTHETIC build to be loaded (see below).
#    --restore-only  perform ONLY the restoration + verification, then exit.
#                    Safe against a live, healthy switch.
#    (default)       refuses to do anything — a mode must be named.
#
#  ---------------------------------------------------------------------------
#  HARDWARE PRECONDITION THIS SCRIPT WILL NOT WORK AROUND
#
#  --gate2 requires p4/case_a_defense3.p4 compiled WITH
#  -DD3_SYNTH_EVENTS to be LOADED. This script does not load it. The loaded
#  program name is read from the bf_switchd process's own --conf-file, which is
#  authoritative about the daemon rather than about any script's belief — but
#  the LIVE and SYNTHETIC builds share that name (same source file), so the name
#  check cannot tell them apart. The synthetic-build check that CAN is done by
#  the control plane: `pipe.IgParser.pgen_event` and `Ingress.tbl_synth_role`
#  exist only in the synthetic build, and poll_defense3.py fails with an
#  explicit "is the SYNTHETIC build loaded?" message if they are missing.
#
#  No Hulk, no injector, no capture, no sudo on any host: every packet is
#  generated inside the chip and every result is read out of registers and
#  counters. dp11 is never touched — it is unconfigured and its link is dark,
#  which is why the synthetic events are generated by pktgen app 2 rather than
#  through the P4's D3_REPLAY_ON_HULK path.
#
#  ---------------------------------------------------------------------------
#  PROCESS-CHECK NOTE (this has bitten this project before)
#  `pgrep -f bf_switchd` OVERCOUNTS — measured 3 for a single running daemon,
#  because the launcher command line contains the string and so does the
#  invoking shell's. Count with `pgrep -cx bf_switchd`, which matches the
#  executable NAME; use the [b]racket trick only for `pkill -f`. This script
#  does not count bf_switchd itself — the delegated restore does — but the note
#  stays so the rule is not rediscovered.
#
#  LD_LIBRARY_PATH is always dereferenced as ${LD_LIBRARY_PATH:-}: an unset
#  variable under `set -u` previously aborted a swap AFTER the old program had
#  been stopped, leaving the switch with nothing loaded.
# =============================================================================
set -Eeuo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/.." && pwd)"
# ROOT is defense3/, so the repository root is ONE level up, not two. The old
# "$ROOT/../.." resolved to ~/Projects and made RESTORE_RUNNER point outside the
# repo, so every mode died at the precondition check with "the proven restore
# runner is missing". Found 2026-07-30 when the gates were first driven from a
# wrapper rather than by hand with RESTORE_RUNNER already set in the environment.
REPO="$(cd "$ROOT/.." && pwd)"

# ---- switch identity --------------------------------------------------------
SW_HOST="${SW_HOST:-decps@10.10.54.81}"
SSH_OPTS="${SSH_OPTS:--o BatchMode=yes -o ConnectTimeout=10 -o ServerAliveInterval=5}"

SDE="${SDE:-/home/decps/Downloads/bf-sde-9.13.2}"
SP="$SDE/install/lib/python3.8/site-packages"
PYPATH="$SP:$SP/tofino"          # bfrt_grpc lives under site-packages/tofino

# FINAL repaired build is the default (CORRECTIONS.md §2.2). The unrepaired program is a
# historical control only; select it with PROG=case_a_defense3_unrepaired on purpose.
PROG="${PROG:-case_a_defense3}"

# ---- staging: the driver AND the Gate-1 setup module it imports --------------
STAGE_DIR="${STAGE_DIR:-/home/decps/d3gate2}"
POLL_LOCAL="$HERE/poll_defense3.py"
SETUP_LOCAL="$ROOT/setup/case_a_defense3_fixed_ack_delay_setup.py"
POLL_REMOTE="$STAGE_DIR/poll_defense3.py"

# the proven restore, delegated to verbatim; the frozen tree is not modified
RESTORE_RUNNER="${RESTORE_RUNNER:-$REPO/research/case_a_read_anchored_dual_release/run/run_four_queue_oracle.sh}"
ANALYZER="$ROOT/analysis/analyze_defense3.py"
C2_ANALYZER="$ROOT/analysis/analyze_check2.py"
G34_ANALYZER="$ROOT/analysis/analyze_gate34.py"

# ---- run-local state --------------------------------------------------------
OUTDIR="${OUTDIR:-$ROOT/evidence/gate2}"
LOCKFILE="${LOCKFILE:-${TMPDIR:-/tmp}/case_a_defense3_gate2.lock}"
RUNTS="$(date -u +%Y%m%dT%H%M%SZ)"

DRYRUN="${DRYRUN:-0}"                       # 1 = no ssh, no hardware at all
NO_TMUX="${D3_NO_TMUX:-0}"
SKIP_RESTORE="${D3_SKIP_RESTORE:-0}"        # 1 = leave the switch on Defense 3

# Gate-2 parameters. Pass-through so a sweep needs no edit to this file.
# D = 2 ms is §13 Gate 2's stated starting value.
D_MS="${D_MS:-2}"
BUDGET="${BUDGET:-18000}"
# gate2-split, not gate2-normal: CHECK 2 measured that a single generator run
# withholds the blocker burst for the run's whole span, so a schedule with the
# READ and the ACK in one run can never have the reservoir standing in time.
SCENARIO="${SCENARIO:-gate2-2timer}"
IPG_NS="${IPG_NS:-500000}"                  # ONE hardware gap: READ->ACK->RESP
GEN="${GEN:-0xC0}"
WAIT_S="${WAIT_S:-0.5}"

log()  { printf '[%s] %s\n' "$(date -u +%H:%M:%S)" "$*" >&2; }
die()  { log "FATAL: $*"; exit 1; }

usage() {
  sed -n '2,80p' "${BASH_SOURCE[0]}" | sed 's/^#\{0,1\} \{0,1\}//'
  exit "${1:-0}"
}

MODE=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --gate2)        MODE="gate2" ;;
    --gate3)        MODE="gate3" ;;
    --gate4)        MODE="gate4" ;;
    --check2)       MODE="check2" ;;
    --microbench)   MODE="microbench" ;;
    --restore-only) MODE="restore-only" ;;
    --no-tmux)      NO_TMUX=1 ;;
    --dry-run)      DRYRUN=1 ;;
    -h|--help)      usage 0 ;;
    *) die "unknown argument: $1 (try --help)" ;;
  esac
  shift
done
[[ -n "$MODE" ]] || die "a mode is required: --gate2 | --gate3 | --gate4 | --check2 | --microbench | --restore-only"

mkdir -p "$OUTDIR"
[[ -f "$RESTORE_RUNNER" ]] \
  || die "the proven restore runner is missing: $RESTORE_RUNNER"

# =============================================================================
#  ONE TMUX SESSION for the whole hardware transaction, so it survives the
#  terminal: if the controlling SSH session dies mid-run a bare script would
#  take SIGHUP with the switch half-configured; inside tmux the script keeps
#  running and its EXIT trap still restores. --no-tmux exists for local
#  dry-runs and for trap tests, which must run inline so a signal can be
#  delivered to this very process.
# =============================================================================
if [[ -z "${TMUX:-}" && "$NO_TMUX" != "1" ]]; then
  command -v tmux >/dev/null 2>&1 || die "tmux not found (or re-run with --no-tmux)"
  SESSION="d3g2_${MODE//-/_}_$RUNTS"
  RCFILE="$OUTDIR/.tmux_rc_$RUNTS"
  TMUXLOG="$OUTDIR/tmux_${SESSION}.log"
  log "re-executing inside tmux session '$SESSION' (log: $TMUXLOG)"
  : > "$TMUXLOG"
  tmux new-session -d -s "$SESSION" \
    "D3_NO_TMUX=1 '${BASH_SOURCE[0]}' --$MODE $( [[ $DRYRUN == 1 ]] && echo --dry-run ) \
       >'$TMUXLOG' 2>&1; echo \$? >'$RCFILE'"
  tail -n +1 -f "$TMUXLOG" &
  TAILPID=$!
  while tmux has-session -t "$SESSION" 2>/dev/null; do sleep 0.5; done
  sleep 0.3
  kill "$TAILPID" 2>/dev/null || true
  RC="$(cat "$RCFILE" 2>/dev/null || echo 1)"
  rm -f "$RCFILE"
  log "tmux session finished, rc=$RC"
  exit "$RC"
fi

# =============================================================================
#  flock — two runs can NEVER overlap. A second run while the first is mid-
#  transaction would race on the generator and on the register reset.
# =============================================================================
exec 9>"$LOCKFILE"
if ! flock -n 9; then
  die "another run holds $LOCKFILE — refusing to start a second hardware transaction"
fi
log "acquired $LOCKFILE (pid $$)"

# =============================================================================
#  remote command transport. Commands are shipped base64-encoded and decoded on
#  the far side: nested single quotes inside `ssh host "bash -c '...'"` have
#  silently mangled commands in this project before, and base64 removes the
#  entire quoting problem.
# =============================================================================
sw() {
  if [[ "$DRYRUN" == "1" ]]; then
    log "DRYRUN sw: $*"
    return 0
  fi
  local b64
  b64="$(printf '%s' "$*" | base64 -w0)"
  # shellcheck disable=SC2086
  ssh $SSH_OPTS "$SW_HOST" "echo $b64 | base64 -d | bash -s"
}

cp_cmd() {
  cat <<EOF
export SDE=$SDE
export SDE_INSTALL=\$SDE/install
export LD_LIBRARY_PATH=\$SDE_INSTALL/lib:\${LD_LIBRARY_PATH:-}
PYTHONPATH=$PYPATH python3.8 $POLL_REMOTE $*
EOF
}

# Reads the LOADED program name independently of any setup script, by finding
# the --conf-file bf_switchd was actually launched with and parsing it. This is
# authoritative about the daemon, not about a script's belief.
switch_state_cmd() {
  cat <<'EOF'
set -uo pipefail
n=$(pgrep -cx bf_switchd || true)
pid=$(pgrep -ox bf_switchd || true)
conf=""
prog=""
if [ -n "$pid" ]; then
  conf=$(tr '\0' '\n' < /proc/$pid/cmdline | awk '/^--conf-file$/{getline; print; exit}')
  if [ -z "$conf" ]; then
    conf=$(tr '\0' '\n' < /proc/$pid/cmdline | sed -n 's/^--conf-file=//p' | head -1)
  fi
  if [ -n "$conf" ] && [ -r "$conf" ]; then
    prog=$(python3 -c "
import json,sys
d=json.load(open(sys.argv[1]))
print(d['p4_devices'][0]['p4_programs'][0]['program-name'])
" "$conf" 2>/dev/null || true)
  fi
fi
printf '{\"n_bf_switchd\":%s,\"pid\":\"%s\",\"conf\":\"%s\",\"p4_name\":\"%s\"}\n' \
  "${n:-0}" "$pid" "$conf" "$prog"
EOF
}

switch_state() {
  if [[ "$DRYRUN" == "1" ]]; then
    echo '{"n_bf_switchd":1,"pid":"999999","conf":"/dryrun.conf","p4_name":"'"$PROG"'"}'
    return 0
  fi
  sw "$(switch_state_cmd)" | tail -1
}

json_field() {  # json_field <json> <key>
  python3 -c '
import json,sys
d=json.loads(sys.argv[1])
v=d.get(sys.argv[2])
print("" if v is None else v)
' "$1" "$2"
}

# =============================================================================
#  RESTORATION — delegated, not reimplemented. See the file header.
# =============================================================================
RESTORE_DONE=0

restore_known_good() {
  if [[ "$RESTORE_DONE" == "1" ]]; then
    log "restore already performed this run; not repeating"
    return 0
  fi
  RESTORE_DONE=1
  if [[ "$SKIP_RESTORE" == "1" ]]; then
    log "D3_SKIP_RESTORE=1 — NOT restoring. The switch is left as this run found"
    log "it, and restoring it is now YOUR responsibility:"
    log "  bash $RESTORE_RUNNER --restore-only"
    return 0
  fi
  log "=========== RESTORING via $RESTORE_RUNNER --restore-only ==========="
  local rc=0
  # A PRIVATE lockfile for the child: this process already holds the shared
  # hardware lock, and the child's own `flock -n` would otherwise fail and skip
  # the restore entirely.
  LOCKFILE="${TMPDIR:-/tmp}/d3g2_child_restore_$$.lock" \
  OUTDIR="$OUTDIR" \
    bash "$RESTORE_RUNNER" --restore-only --no-tmux \
      $( [[ "$DRYRUN" == "1" ]] && echo --dry-run ) || rc=$?
  rm -f "${TMPDIR:-/tmp}/d3g2_child_restore_$$.lock"
  if [[ $rc -eq 0 ]]; then
    log "RESTORE VERIFIED by the proven runner."
  else
    log "RESTORE VERIFICATION FAILED (rc=$rc)."
    log "DO NOT leave the switch in this state. Re-run: $RESTORE_RUNNER --restore-only"
  fi
  return $rc
}

# ---- the traps --------------------------------------------------------------
# Signal traps `exit`, which makes the EXIT trap fire, which restores. The
# RESTORE_DONE guard keeps restoration to exactly one execution.
on_exit() {
  local rc=$?
  trap - EXIT
  log "on_exit: rc=$rc — running restoration"
  restore_known_good || rc=$(( rc == 0 ? 1 : rc ))
  log "exit $rc"
  exit "$rc"
}
trap 'on_exit' EXIT
trap 'log "caught SIGINT";  exit 130' INT
trap 'log "caught SIGTERM"; exit 143' TERM
trap 'log "caught SIGHUP";  exit 129' HUP

log "mode=$MODE dryrun=$DRYRUN prog=$PROG skip_restore=$SKIP_RESTORE"

# TEST HOOK. Not used in any real run. Holds the script in a known long-running
# state so INT / TERM / HUP can be delivered deterministically, which is how the
# "the trap really does restore on a signal" property is demonstrated. The sleep
# is BACKGROUNDED and waited on, because bash does not run a trap until the
# current foreground builtin returns — a plain `sleep 300` would delay the trap
# by the full 300 s and make the test look like a failure.
if [[ -n "${D3_TEST_HANG:-}" ]]; then
  log "TEST HOOK: holding for ${D3_TEST_HANG}s so a signal can be delivered"
  sleep "$D3_TEST_HANG" &
  wait $! || true
  log "TEST HOOK: hold elapsed without a signal"
fi

if [[ "$MODE" == "restore-only" ]]; then
  log "restore-only: delegating to the proven runner"
  restore_known_good
  exit $?
fi

# =============================================================================
#  Everything below needs the SYNTHETIC build LOADED. This script does not load it.
# =============================================================================
PRE_STATE="$(switch_state)"
PRE_PROG="$(json_field "$PRE_STATE" p4_name)"
echo "$PRE_STATE" > "$OUTDIR/switch_state_snapshot_$RUNTS.json"
log "pre-run switch state: $PRE_STATE"

if [[ "$PRE_PROG" != "$PROG" && "$DRYRUN" != "1" ]]; then
  die "--$MODE needs '$PROG' loaded, but the switch is running '$PRE_PROG'. \
Loading it displaces what is there and is a separate, explicitly authorized \
step — this script will not do it. (The EXIT trap will still restore the \
known-good state before returning.)"
fi

if [[ "$MODE" == "microbench" ]]; then
  RUN_OUT="$OUTDIR/microbench_$RUNTS"
elif [[ "$MODE" == "check2" ]]; then
  RUN_OUT="$OUTDIR/check2_$RUNTS"
elif [[ "$MODE" == "gate3" ]]; then
  RUN_OUT="$OUTDIR/gate3_$RUNTS"
elif [[ "$MODE" == "gate4" ]]; then
  RUN_OUT="$OUTDIR/gate4_$RUNTS"
else
  RUN_OUT="$OUTDIR/gate2_$RUNTS"
fi
mkdir -p "$RUN_OUT"
if [[ "$MODE" == "gate3" ]]; then
  log "=== GATE 3: ${G3_TXNS:-5} CONSECUTIVE normal transactions, no reload ==="
  log "no transaction-state reset between them; the generation ADVANCES each time"
elif [[ "$MODE" == "gate4" ]]; then
  log "=== GATE 4: three boundary cases x ${G4_REPS:-3}, then a recovery txn ==="
elif [[ "$MODE" == "check2" ]]; then
  log "=== CHECK 2: PRODUCTION BLOCKER-START LATENCY (many trials, no ACK) ==="
  log "trials=${C2_TRIALS:-100} batch_trials=${C2_BATCH_TRIALS:-10} \
batch_ipgs=${C2_BATCH_IPGS:-200000,500000} dwell=${C2_WAIT_S:-0.2}s"
else
  log "=== GATE 2: ONE synthetic transaction, then STOP ==="
fi
log "D=$D_MS ms  budget=$BUDGET  scenario=$SCENARIO  ipg=$IPG_NS ns  gen=$GEN"
log "evidence: $RUN_OUT"

# ---- stage the driver and the Gate-1 module it imports ----------------------
# poll_defense3.py imports case_a_defense3_fixed_ack_delay_setup, so BOTH files
# must land in the same directory: there is one definition of every bfrt idiom
# and it is not duplicated into the driver.
log "--- staging $POLL_LOCAL + the Gate-1 setup module -> $SW_HOST:$STAGE_DIR ---"
[[ -f "$POLL_LOCAL" ]]  || die "missing $POLL_LOCAL"
[[ -f "$SETUP_LOCAL" ]] || die "missing $SETUP_LOCAL"
sw "mkdir -p $STAGE_DIR"
if [[ "$DRYRUN" != "1" ]]; then
  # shellcheck disable=SC2086
  scp $SSH_OPTS "$POLL_LOCAL" "$SETUP_LOCAL" "$SW_HOST:$STAGE_DIR/" >/dev/null \
    || die "staging failed"
fi

# ---- preflight cleanup + clean assertion ------------------------------------
# The transaction REFUSES to start on a dirty switch, so without this it would
# refuse whenever anything earlier left state behind. This is the ONLY place
# cleanup runs outside a transaction; inside one it is the transaction's own
# `finally` that does it.
log "--- preflight cleanup + clean assertion ---"
sw "$(cp_cmd --cleanup --assert-clean --prog "$PROG")" \
   >"$RUN_OUT/preflight_clean.txt" 2>&1 \
  || log "WARN: preflight reported failures; see $RUN_OUT/preflight_clean.txt"

# ---- THE transaction --------------------------------------------------------
# The WHOLE transaction runs in ONE remote process: assert the speed, assert a
# clean start, configure, arm, wait, read the registers and counters, clean up
# from a `finally`. Keeping it in one process means the arm and the read are
# local gRPC calls rather than ones that cross an SSH hop, which matters when
# the quantity being measured is 2 ms.
RJSON="/tmp/d3gate2_${RUNTS}.json"
if [[ "$MODE" == "microbench" ]]; then
  LJSON="$RUN_OUT/microbench.json"
  TXNLOG="$RUN_OUT/microbench.log"
  POLL_MODE_ARGS=(--microbench)
  [[ -n "${MB_ARMS:-}" ]] && POLL_MODE_ARGS+=(--mb-arms "$MB_ARMS")
elif [[ "$MODE" == "gate3" ]]; then
  LJSON="$RUN_OUT/gate3.json"
  TXNLOG="$RUN_OUT/gate3.log"
  POLL_MODE_ARGS=(--gate3 --g3-txns "${G3_TXNS:-5}")
elif [[ "$MODE" == "gate4" ]]; then
  LJSON="$RUN_OUT/gate4.json"
  TXNLOG="$RUN_OUT/gate4.log"
  POLL_MODE_ARGS=(--gate4 --g4-reps "${G4_REPS:-3}")
  # STALE_OFFSET_NS places case F's injected RESPONSE relative to the READ. It is
  # exposed because the default (800000) puts it only 200 us from N+1's OWN
  # RESPONSE, and the control plane's own arming skew across three one-shot timers
  # is of that same order -- so the two RESPONSES can arrive in either order, which
  # is exactly why the case was unscorable. Widen the separation to make the
  # ordering robust rather than incidental.
  [[ -n "${STALE_OFFSET_NS:-}" ]] && POLL_MODE_ARGS+=(--stale-offset-ns "$STALE_OFFSET_NS")
elif [[ "$MODE" == "check2" ]]; then
  LJSON="$RUN_OUT/check2.json"
  TXNLOG="$RUN_OUT/check2.log"
  POLL_MODE_ARGS=(--check2
                  --c2-trials "${C2_TRIALS:-100}"
                  --c2-batch-trials "${C2_BATCH_TRIALS:-10}"
                  --c2-batch-ipgs "${C2_BATCH_IPGS:-200000,500000}"
                  --c2-wait-s "${C2_WAIT_S:-0.2}")
  # KVAL sweeps the reservoir size K for the fail-open reconciliation microbenchmark;
  # default (unset) keeps the built-in K=64.
  [[ -n "${KVAL:-}" ]] && POLL_MODE_ARGS+=(--k "$KVAL")
else
  LJSON="$RUN_OUT/gate2_txn.json"
  TXNLOG="$RUN_OUT/gate2_txn.log"
  POLL_MODE_ARGS=(--gate2)
fi
set +e
sw "$(cp_cmd "${POLL_MODE_ARGS[@]}" --prog "$PROG" --scenario "$SCENARIO" \
        --ipg-ns "$IPG_NS" \
        --gen "$GEN" --d-ms "$D_MS" --budget "$BUDGET" --wait-s "$WAIT_S" \
        --txn-index 1 --out "$RJSON")" \
   >"$TXNLOG" 2>&1
TRC=$?
set -e
log "transaction returned rc=$TRC"

if [[ "$DRYRUN" != "1" ]]; then
  # shellcheck disable=SC2086
  scp $SSH_OPTS "$SW_HOST:$RJSON" "$LJSON" >/dev/null 2>&1 \
    || log "WARN: could not fetch $RJSON — falling back to the log"
  sw "rm -f $RJSON" >/dev/null 2>&1 || true
fi
if [[ ! -s "$LJSON" && -s "$TXNLOG" ]]; then
  # the manifest is also echoed as a `D3GATE2 {...}` line; the analyzer reads
  # either form, so a failed scp does not lose the trial.
  cp "$TXNLOG" "$RUN_OUT/gate2_txn.fallback.log"
fi

{
  echo "mode=$MODE scenario=$SCENARIO d_ms=$D_MS budget=$BUDGET ipg_ns=$IPG_NS"
  echo "gen=$GEN wait_s=$WAIT_S txn_rc=$TRC"
  echo "utc=$(date -u +%Y-%m-%dT%H:%M:%SZ)"
} > "$RUN_OUT/run.summary"

# ---- score it ---------------------------------------------------------------
# In DRYRUN there is no measurement to score — feeding an empty manifest to the
# analyzer would print a FAIL that means nothing. Instead the dry run exercises
# the two things it CAN: the driver's whole offline path (argument surface,
# template construction, D quantization, the ipg inequalities) and the
# analyzer's own controls.
if [[ "$DRYRUN" == "1" ]]; then
  log "--- DRYRUN: local offline validation instead of scoring ---"
  set +e
  python3 "$POLL_LOCAL" --dry-run --scenario "$SCENARIO" --ipg-ns "$IPG_NS" \
      --gen "$GEN" --d-ms "$D_MS" --budget "$BUDGET" \
      --out "$RUN_OUT/dryrun_poll.json" >"$RUN_OUT/dryrun_poll.txt" 2>&1
  PRC=$?
  python3 "$ANALYZER" --self-test >"$RUN_OUT/dryrun_selftest.txt" 2>&1
  ARC=$?
  python3 "$C2_ANALYZER" --self-test >>"$RUN_OUT/dryrun_selftest.txt" 2>&1 || ARC=$?
  python3 "$ROOT/analysis/test_tag_domain.py" \
      >"$RUN_OUT/dryrun_tag_domain.txt" 2>&1 || ARC=$?
  set -e
  log "dryrun: poll offline rc=$PRC, analyzer self-test rc=$ARC"
  TRC=$PRC
elif [[ "$MODE" == "microbench" ]]; then
  # The microbenchmark is a DIAGNOSTIC, not a scored gate: it produces the
  # per-pipe readbacks that settle F01 and nothing the Gate-2 rubric applies to.
  log "--- microbench: no scoring (diagnostic run); see $LJSON ---"
  ARC=0
elif [[ "$MODE" == "gate3" || "$MODE" == "gate4" ]]; then
  log "--- scoring $MODE ---"
  set +e
  python3 "$G34_ANALYZER" "$LJSON" \
    --json-out "$RUN_OUT/${MODE}_analysis.json" \
    | tee "$RUN_OUT/${MODE}_analysis.txt"
  ARC=${PIPESTATUS[0]}
  set -e
elif [[ "$MODE" == "check2" ]]; then
  # CHECK 2 has its OWN rubric — the Gate-2 analyzer would score a no-ACK run as a
  # failed hold, which it is not; there is no ACK to hold.
  log "--- scoring CHECK 2 ---"
  set +e
  python3 "$C2_ANALYZER" "$LJSON" \
    --json-out "$RUN_OUT/check2_analysis.json" \
    | tee "$RUN_OUT/check2_analysis.txt"
  ARC=${PIPESTATUS[0]}
  set -e
else
  log "--- scoring ---"
  set +e
  python3 "$ANALYZER" --evidence-dir "$RUN_OUT" \
    --json-out "$RUN_OUT/gate2_analysis.json" \
    | tee "$RUN_OUT/gate2_analysis.txt"
  ARC=${PIPESTATUS[0]}
  set -e
fi

log "-------------------------------------------------------------"
if [[ "$MODE" == "gate3" || "$MODE" == "gate4" ]]; then
  log "${MODE^^} COMPLETE. txn_rc=$TRC analyzer_rc=$ARC"
elif [[ "$MODE" == "check2" ]]; then
  log "CHECK 2 COMPLETE. txn_rc=$TRC analyzer_rc=$ARC"
else
  log "GATE 2 COMPLETE — ONE transaction. txn_rc=$TRC analyzer_rc=$ARC"
fi
log "evidence: $RUN_OUT"
log ""
log "STOPPING HERE BY DESIGN. Gates 3 (five transactions) and 4 (three"
log "boundary cases) are separate, human-gated steps and are NOT in this script."
log ""
log "The EXIT trap now restores the known-good state via the proven runner."
if [[ $TRC -ne 0 || $ARC -ne 0 ]]; then
  exit 1
fi
exit 0
